/*
Open WebUI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebui

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UserInfoResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInfoResponse{}

// UserInfoResponse struct for UserInfoResponse
type UserInfoResponse struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Email string `json:"email"`
	Role string `json:"role"`
}

type _UserInfoResponse UserInfoResponse

// NewUserInfoResponse instantiates a new UserInfoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInfoResponse(id string, name string, email string, role string) *UserInfoResponse {
	this := UserInfoResponse{}
	this.Id = id
	this.Name = name
	this.Email = email
	this.Role = role
	return &this
}

// NewUserInfoResponseWithDefaults instantiates a new UserInfoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInfoResponseWithDefaults() *UserInfoResponse {
	this := UserInfoResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UserInfoResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserInfoResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserInfoResponse) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *UserInfoResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserInfoResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserInfoResponse) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *UserInfoResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserInfoResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserInfoResponse) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value
func (o *UserInfoResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *UserInfoResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *UserInfoResponse) SetRole(v string) {
	o.Role = v
}

func (o UserInfoResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInfoResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *UserInfoResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"email",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserInfoResponse := _UserInfoResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserInfoResponse)

	if err != nil {
		return err
	}

	*o = UserInfoResponse(varUserInfoResponse)

	return err
}

type NullableUserInfoResponse struct {
	value *UserInfoResponse
	isSet bool
}

func (v NullableUserInfoResponse) Get() *UserInfoResponse {
	return v.value
}

func (v *NullableUserInfoResponse) Set(val *UserInfoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInfoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInfoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInfoResponse(val *UserInfoResponse) *NullableUserInfoResponse {
	return &NullableUserInfoResponse{value: val, isSet: true}
}

func (v NullableUserInfoResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInfoResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


