/*
Open WebUI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebui-go-sdk

import (
	"encoding/json"
)

// checks if the SharingPermissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SharingPermissions{}

// SharingPermissions struct for SharingPermissions
type SharingPermissions struct {
	PublicModels *bool `json:"public_models,omitempty"`
	PublicKnowledge *bool `json:"public_knowledge,omitempty"`
	PublicPrompts *bool `json:"public_prompts,omitempty"`
	PublicTools *bool `json:"public_tools,omitempty"`
}

// NewSharingPermissions instantiates a new SharingPermissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharingPermissions() *SharingPermissions {
	this := SharingPermissions{}
	var publicModels bool = true
	this.PublicModels = &publicModels
	var publicKnowledge bool = true
	this.PublicKnowledge = &publicKnowledge
	var publicPrompts bool = true
	this.PublicPrompts = &publicPrompts
	var publicTools bool = true
	this.PublicTools = &publicTools
	return &this
}

// NewSharingPermissionsWithDefaults instantiates a new SharingPermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharingPermissionsWithDefaults() *SharingPermissions {
	this := SharingPermissions{}
	var publicModels bool = true
	this.PublicModels = &publicModels
	var publicKnowledge bool = true
	this.PublicKnowledge = &publicKnowledge
	var publicPrompts bool = true
	this.PublicPrompts = &publicPrompts
	var publicTools bool = true
	this.PublicTools = &publicTools
	return &this
}

// GetPublicModels returns the PublicModels field value if set, zero value otherwise.
func (o *SharingPermissions) GetPublicModels() bool {
	if o == nil || IsNil(o.PublicModels) {
		var ret bool
		return ret
	}
	return *o.PublicModels
}

// GetPublicModelsOk returns a tuple with the PublicModels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharingPermissions) GetPublicModelsOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicModels) {
		return nil, false
	}
	return o.PublicModels, true
}

// HasPublicModels returns a boolean if a field has been set.
func (o *SharingPermissions) HasPublicModels() bool {
	if o != nil && !IsNil(o.PublicModels) {
		return true
	}

	return false
}

// SetPublicModels gets a reference to the given bool and assigns it to the PublicModels field.
func (o *SharingPermissions) SetPublicModels(v bool) {
	o.PublicModels = &v
}

// GetPublicKnowledge returns the PublicKnowledge field value if set, zero value otherwise.
func (o *SharingPermissions) GetPublicKnowledge() bool {
	if o == nil || IsNil(o.PublicKnowledge) {
		var ret bool
		return ret
	}
	return *o.PublicKnowledge
}

// GetPublicKnowledgeOk returns a tuple with the PublicKnowledge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharingPermissions) GetPublicKnowledgeOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicKnowledge) {
		return nil, false
	}
	return o.PublicKnowledge, true
}

// HasPublicKnowledge returns a boolean if a field has been set.
func (o *SharingPermissions) HasPublicKnowledge() bool {
	if o != nil && !IsNil(o.PublicKnowledge) {
		return true
	}

	return false
}

// SetPublicKnowledge gets a reference to the given bool and assigns it to the PublicKnowledge field.
func (o *SharingPermissions) SetPublicKnowledge(v bool) {
	o.PublicKnowledge = &v
}

// GetPublicPrompts returns the PublicPrompts field value if set, zero value otherwise.
func (o *SharingPermissions) GetPublicPrompts() bool {
	if o == nil || IsNil(o.PublicPrompts) {
		var ret bool
		return ret
	}
	return *o.PublicPrompts
}

// GetPublicPromptsOk returns a tuple with the PublicPrompts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharingPermissions) GetPublicPromptsOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicPrompts) {
		return nil, false
	}
	return o.PublicPrompts, true
}

// HasPublicPrompts returns a boolean if a field has been set.
func (o *SharingPermissions) HasPublicPrompts() bool {
	if o != nil && !IsNil(o.PublicPrompts) {
		return true
	}

	return false
}

// SetPublicPrompts gets a reference to the given bool and assigns it to the PublicPrompts field.
func (o *SharingPermissions) SetPublicPrompts(v bool) {
	o.PublicPrompts = &v
}

// GetPublicTools returns the PublicTools field value if set, zero value otherwise.
func (o *SharingPermissions) GetPublicTools() bool {
	if o == nil || IsNil(o.PublicTools) {
		var ret bool
		return ret
	}
	return *o.PublicTools
}

// GetPublicToolsOk returns a tuple with the PublicTools field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SharingPermissions) GetPublicToolsOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicTools) {
		return nil, false
	}
	return o.PublicTools, true
}

// HasPublicTools returns a boolean if a field has been set.
func (o *SharingPermissions) HasPublicTools() bool {
	if o != nil && !IsNil(o.PublicTools) {
		return true
	}

	return false
}

// SetPublicTools gets a reference to the given bool and assigns it to the PublicTools field.
func (o *SharingPermissions) SetPublicTools(v bool) {
	o.PublicTools = &v
}

func (o SharingPermissions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SharingPermissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PublicModels) {
		toSerialize["public_models"] = o.PublicModels
	}
	if !IsNil(o.PublicKnowledge) {
		toSerialize["public_knowledge"] = o.PublicKnowledge
	}
	if !IsNil(o.PublicPrompts) {
		toSerialize["public_prompts"] = o.PublicPrompts
	}
	if !IsNil(o.PublicTools) {
		toSerialize["public_tools"] = o.PublicTools
	}
	return toSerialize, nil
}

type NullableSharingPermissions struct {
	value *SharingPermissions
	isSet bool
}

func (v NullableSharingPermissions) Get() *SharingPermissions {
	return v.value
}

func (v *NullableSharingPermissions) Set(val *SharingPermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableSharingPermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableSharingPermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharingPermissions(val *SharingPermissions) *NullableSharingPermissions {
	return &NullableSharingPermissions{value: val, isSet: true}
}

func (v NullableSharingPermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharingPermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


