/*
Open WebUI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebui

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenWebuiRoutersChatsMessageForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenWebuiRoutersChatsMessageForm{}

// OpenWebuiRoutersChatsMessageForm struct for OpenWebuiRoutersChatsMessageForm
type OpenWebuiRoutersChatsMessageForm struct {
	Content string `json:"content"`
}

type _OpenWebuiRoutersChatsMessageForm OpenWebuiRoutersChatsMessageForm

// NewOpenWebuiRoutersChatsMessageForm instantiates a new OpenWebuiRoutersChatsMessageForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenWebuiRoutersChatsMessageForm(content string) *OpenWebuiRoutersChatsMessageForm {
	this := OpenWebuiRoutersChatsMessageForm{}
	this.Content = content
	return &this
}

// NewOpenWebuiRoutersChatsMessageFormWithDefaults instantiates a new OpenWebuiRoutersChatsMessageForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenWebuiRoutersChatsMessageFormWithDefaults() *OpenWebuiRoutersChatsMessageForm {
	this := OpenWebuiRoutersChatsMessageForm{}
	return &this
}

// GetContent returns the Content field value
func (o *OpenWebuiRoutersChatsMessageForm) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersChatsMessageForm) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *OpenWebuiRoutersChatsMessageForm) SetContent(v string) {
	o.Content = v
}

func (o OpenWebuiRoutersChatsMessageForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenWebuiRoutersChatsMessageForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *OpenWebuiRoutersChatsMessageForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenWebuiRoutersChatsMessageForm := _OpenWebuiRoutersChatsMessageForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenWebuiRoutersChatsMessageForm)

	if err != nil {
		return err
	}

	*o = OpenWebuiRoutersChatsMessageForm(varOpenWebuiRoutersChatsMessageForm)

	return err
}

type NullableOpenWebuiRoutersChatsMessageForm struct {
	value *OpenWebuiRoutersChatsMessageForm
	isSet bool
}

func (v NullableOpenWebuiRoutersChatsMessageForm) Get() *OpenWebuiRoutersChatsMessageForm {
	return v.value
}

func (v *NullableOpenWebuiRoutersChatsMessageForm) Set(val *OpenWebuiRoutersChatsMessageForm) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenWebuiRoutersChatsMessageForm) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenWebuiRoutersChatsMessageForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenWebuiRoutersChatsMessageForm(val *OpenWebuiRoutersChatsMessageForm) *NullableOpenWebuiRoutersChatsMessageForm {
	return &NullableOpenWebuiRoutersChatsMessageForm{value: val, isSet: true}
}

func (v NullableOpenWebuiRoutersChatsMessageForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenWebuiRoutersChatsMessageForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


