/*
Open WebUI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebui-go-sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenWebuiRoutersImagesConfigForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenWebuiRoutersImagesConfigForm{}

// OpenWebuiRoutersImagesConfigForm struct for OpenWebuiRoutersImagesConfigForm
type OpenWebuiRoutersImagesConfigForm struct {
	Enabled bool `json:"enabled"`
	Engine string `json:"engine"`
	PromptGeneration bool `json:"prompt_generation"`
	Openai OpenWebuiRoutersImagesOpenAIConfigForm `json:"openai"`
	Automatic1111 Automatic1111ConfigForm `json:"automatic1111"`
	Comfyui ComfyUIConfigForm `json:"comfyui"`
	Gemini GeminiConfigForm `json:"gemini"`
}

type _OpenWebuiRoutersImagesConfigForm OpenWebuiRoutersImagesConfigForm

// NewOpenWebuiRoutersImagesConfigForm instantiates a new OpenWebuiRoutersImagesConfigForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenWebuiRoutersImagesConfigForm(enabled bool, engine string, promptGeneration bool, openai OpenWebuiRoutersImagesOpenAIConfigForm, automatic1111 Automatic1111ConfigForm, comfyui ComfyUIConfigForm, gemini GeminiConfigForm) *OpenWebuiRoutersImagesConfigForm {
	this := OpenWebuiRoutersImagesConfigForm{}
	this.Enabled = enabled
	this.Engine = engine
	this.PromptGeneration = promptGeneration
	this.Openai = openai
	this.Automatic1111 = automatic1111
	this.Comfyui = comfyui
	this.Gemini = gemini
	return &this
}

// NewOpenWebuiRoutersImagesConfigFormWithDefaults instantiates a new OpenWebuiRoutersImagesConfigForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenWebuiRoutersImagesConfigFormWithDefaults() *OpenWebuiRoutersImagesConfigForm {
	this := OpenWebuiRoutersImagesConfigForm{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *OpenWebuiRoutersImagesConfigForm) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersImagesConfigForm) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *OpenWebuiRoutersImagesConfigForm) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEngine returns the Engine field value
func (o *OpenWebuiRoutersImagesConfigForm) GetEngine() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Engine
}

// GetEngineOk returns a tuple with the Engine field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersImagesConfigForm) GetEngineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engine, true
}

// SetEngine sets field value
func (o *OpenWebuiRoutersImagesConfigForm) SetEngine(v string) {
	o.Engine = v
}

// GetPromptGeneration returns the PromptGeneration field value
func (o *OpenWebuiRoutersImagesConfigForm) GetPromptGeneration() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PromptGeneration
}

// GetPromptGenerationOk returns a tuple with the PromptGeneration field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersImagesConfigForm) GetPromptGenerationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PromptGeneration, true
}

// SetPromptGeneration sets field value
func (o *OpenWebuiRoutersImagesConfigForm) SetPromptGeneration(v bool) {
	o.PromptGeneration = v
}

// GetOpenai returns the Openai field value
func (o *OpenWebuiRoutersImagesConfigForm) GetOpenai() OpenWebuiRoutersImagesOpenAIConfigForm {
	if o == nil {
		var ret OpenWebuiRoutersImagesOpenAIConfigForm
		return ret
	}

	return o.Openai
}

// GetOpenaiOk returns a tuple with the Openai field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersImagesConfigForm) GetOpenaiOk() (*OpenWebuiRoutersImagesOpenAIConfigForm, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Openai, true
}

// SetOpenai sets field value
func (o *OpenWebuiRoutersImagesConfigForm) SetOpenai(v OpenWebuiRoutersImagesOpenAIConfigForm) {
	o.Openai = v
}

// GetAutomatic1111 returns the Automatic1111 field value
func (o *OpenWebuiRoutersImagesConfigForm) GetAutomatic1111() Automatic1111ConfigForm {
	if o == nil {
		var ret Automatic1111ConfigForm
		return ret
	}

	return o.Automatic1111
}

// GetAutomatic1111Ok returns a tuple with the Automatic1111 field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersImagesConfigForm) GetAutomatic1111Ok() (*Automatic1111ConfigForm, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Automatic1111, true
}

// SetAutomatic1111 sets field value
func (o *OpenWebuiRoutersImagesConfigForm) SetAutomatic1111(v Automatic1111ConfigForm) {
	o.Automatic1111 = v
}

// GetComfyui returns the Comfyui field value
func (o *OpenWebuiRoutersImagesConfigForm) GetComfyui() ComfyUIConfigForm {
	if o == nil {
		var ret ComfyUIConfigForm
		return ret
	}

	return o.Comfyui
}

// GetComfyuiOk returns a tuple with the Comfyui field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersImagesConfigForm) GetComfyuiOk() (*ComfyUIConfigForm, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comfyui, true
}

// SetComfyui sets field value
func (o *OpenWebuiRoutersImagesConfigForm) SetComfyui(v ComfyUIConfigForm) {
	o.Comfyui = v
}

// GetGemini returns the Gemini field value
func (o *OpenWebuiRoutersImagesConfigForm) GetGemini() GeminiConfigForm {
	if o == nil {
		var ret GeminiConfigForm
		return ret
	}

	return o.Gemini
}

// GetGeminiOk returns a tuple with the Gemini field value
// and a boolean to check if the value has been set.
func (o *OpenWebuiRoutersImagesConfigForm) GetGeminiOk() (*GeminiConfigForm, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gemini, true
}

// SetGemini sets field value
func (o *OpenWebuiRoutersImagesConfigForm) SetGemini(v GeminiConfigForm) {
	o.Gemini = v
}

func (o OpenWebuiRoutersImagesConfigForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenWebuiRoutersImagesConfigForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["engine"] = o.Engine
	toSerialize["prompt_generation"] = o.PromptGeneration
	toSerialize["openai"] = o.Openai
	toSerialize["automatic1111"] = o.Automatic1111
	toSerialize["comfyui"] = o.Comfyui
	toSerialize["gemini"] = o.Gemini
	return toSerialize, nil
}

func (o *OpenWebuiRoutersImagesConfigForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"engine",
		"prompt_generation",
		"openai",
		"automatic1111",
		"comfyui",
		"gemini",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenWebuiRoutersImagesConfigForm := _OpenWebuiRoutersImagesConfigForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenWebuiRoutersImagesConfigForm)

	if err != nil {
		return err
	}

	*o = OpenWebuiRoutersImagesConfigForm(varOpenWebuiRoutersImagesConfigForm)

	return err
}

type NullableOpenWebuiRoutersImagesConfigForm struct {
	value *OpenWebuiRoutersImagesConfigForm
	isSet bool
}

func (v NullableOpenWebuiRoutersImagesConfigForm) Get() *OpenWebuiRoutersImagesConfigForm {
	return v.value
}

func (v *NullableOpenWebuiRoutersImagesConfigForm) Set(val *OpenWebuiRoutersImagesConfigForm) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenWebuiRoutersImagesConfigForm) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenWebuiRoutersImagesConfigForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenWebuiRoutersImagesConfigForm(val *OpenWebuiRoutersImagesConfigForm) *NullableOpenWebuiRoutersImagesConfigForm {
	return &NullableOpenWebuiRoutersImagesConfigForm{value: val, isSet: true}
}

func (v NullableOpenWebuiRoutersImagesConfigForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenWebuiRoutersImagesConfigForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


