/*
Open WebUI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebui-go-sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the STTConfigForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &STTConfigForm{}

// STTConfigForm struct for STTConfigForm
type STTConfigForm struct {
	OPENAI_API_BASE_URL string `json:"OPENAI_API_BASE_URL"`
	OPENAI_API_KEY string `json:"OPENAI_API_KEY"`
	ENGINE string `json:"ENGINE"`
	MODEL string `json:"MODEL"`
	SUPPORTED_CONTENT_TYPES []string `json:"SUPPORTED_CONTENT_TYPES,omitempty"`
	WHISPER_MODEL string `json:"WHISPER_MODEL"`
	DEEPGRAM_API_KEY string `json:"DEEPGRAM_API_KEY"`
	AZURE_API_KEY string `json:"AZURE_API_KEY"`
	AZURE_REGION string `json:"AZURE_REGION"`
	AZURE_LOCALES string `json:"AZURE_LOCALES"`
	AZURE_BASE_URL string `json:"AZURE_BASE_URL"`
	AZURE_MAX_SPEAKERS string `json:"AZURE_MAX_SPEAKERS"`
}

type _STTConfigForm STTConfigForm

// NewSTTConfigForm instantiates a new STTConfigForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSTTConfigForm(oPENAIAPIBASEURL string, oPENAIAPIKEY string, eNGINE string, mODEL string, wHISPERMODEL string, dEEPGRAMAPIKEY string, aZUREAPIKEY string, aZUREREGION string, aZURELOCALES string, aZUREBASEURL string, aZUREMAXSPEAKERS string) *STTConfigForm {
	this := STTConfigForm{}
	this.OPENAI_API_BASE_URL = oPENAIAPIBASEURL
	this.OPENAI_API_KEY = oPENAIAPIKEY
	this.ENGINE = eNGINE
	this.MODEL = mODEL
	this.WHISPER_MODEL = wHISPERMODEL
	this.DEEPGRAM_API_KEY = dEEPGRAMAPIKEY
	this.AZURE_API_KEY = aZUREAPIKEY
	this.AZURE_REGION = aZUREREGION
	this.AZURE_LOCALES = aZURELOCALES
	this.AZURE_BASE_URL = aZUREBASEURL
	this.AZURE_MAX_SPEAKERS = aZUREMAXSPEAKERS
	return &this
}

// NewSTTConfigFormWithDefaults instantiates a new STTConfigForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSTTConfigFormWithDefaults() *STTConfigForm {
	this := STTConfigForm{}
	return &this
}

// GetOPENAI_API_BASE_URL returns the OPENAI_API_BASE_URL field value
func (o *STTConfigForm) GetOPENAI_API_BASE_URL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OPENAI_API_BASE_URL
}

// GetOPENAI_API_BASE_URLOk returns a tuple with the OPENAI_API_BASE_URL field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetOPENAI_API_BASE_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OPENAI_API_BASE_URL, true
}

// SetOPENAI_API_BASE_URL sets field value
func (o *STTConfigForm) SetOPENAI_API_BASE_URL(v string) {
	o.OPENAI_API_BASE_URL = v
}

// GetOPENAI_API_KEY returns the OPENAI_API_KEY field value
func (o *STTConfigForm) GetOPENAI_API_KEY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OPENAI_API_KEY
}

// GetOPENAI_API_KEYOk returns a tuple with the OPENAI_API_KEY field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetOPENAI_API_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OPENAI_API_KEY, true
}

// SetOPENAI_API_KEY sets field value
func (o *STTConfigForm) SetOPENAI_API_KEY(v string) {
	o.OPENAI_API_KEY = v
}

// GetENGINE returns the ENGINE field value
func (o *STTConfigForm) GetENGINE() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ENGINE
}

// GetENGINEOk returns a tuple with the ENGINE field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetENGINEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ENGINE, true
}

// SetENGINE sets field value
func (o *STTConfigForm) SetENGINE(v string) {
	o.ENGINE = v
}

// GetMODEL returns the MODEL field value
func (o *STTConfigForm) GetMODEL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MODEL
}

// GetMODELOk returns a tuple with the MODEL field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetMODELOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MODEL, true
}

// SetMODEL sets field value
func (o *STTConfigForm) SetMODEL(v string) {
	o.MODEL = v
}

// GetSUPPORTED_CONTENT_TYPES returns the SUPPORTED_CONTENT_TYPES field value if set, zero value otherwise.
func (o *STTConfigForm) GetSUPPORTED_CONTENT_TYPES() []string {
	if o == nil || IsNil(o.SUPPORTED_CONTENT_TYPES) {
		var ret []string
		return ret
	}
	return o.SUPPORTED_CONTENT_TYPES
}

// GetSUPPORTED_CONTENT_TYPESOk returns a tuple with the SUPPORTED_CONTENT_TYPES field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetSUPPORTED_CONTENT_TYPESOk() ([]string, bool) {
	if o == nil || IsNil(o.SUPPORTED_CONTENT_TYPES) {
		return nil, false
	}
	return o.SUPPORTED_CONTENT_TYPES, true
}

// HasSUPPORTED_CONTENT_TYPES returns a boolean if a field has been set.
func (o *STTConfigForm) HasSUPPORTED_CONTENT_TYPES() bool {
	if o != nil && !IsNil(o.SUPPORTED_CONTENT_TYPES) {
		return true
	}

	return false
}

// SetSUPPORTED_CONTENT_TYPES gets a reference to the given []string and assigns it to the SUPPORTED_CONTENT_TYPES field.
func (o *STTConfigForm) SetSUPPORTED_CONTENT_TYPES(v []string) {
	o.SUPPORTED_CONTENT_TYPES = v
}

// GetWHISPER_MODEL returns the WHISPER_MODEL field value
func (o *STTConfigForm) GetWHISPER_MODEL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WHISPER_MODEL
}

// GetWHISPER_MODELOk returns a tuple with the WHISPER_MODEL field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetWHISPER_MODELOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WHISPER_MODEL, true
}

// SetWHISPER_MODEL sets field value
func (o *STTConfigForm) SetWHISPER_MODEL(v string) {
	o.WHISPER_MODEL = v
}

// GetDEEPGRAM_API_KEY returns the DEEPGRAM_API_KEY field value
func (o *STTConfigForm) GetDEEPGRAM_API_KEY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DEEPGRAM_API_KEY
}

// GetDEEPGRAM_API_KEYOk returns a tuple with the DEEPGRAM_API_KEY field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetDEEPGRAM_API_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DEEPGRAM_API_KEY, true
}

// SetDEEPGRAM_API_KEY sets field value
func (o *STTConfigForm) SetDEEPGRAM_API_KEY(v string) {
	o.DEEPGRAM_API_KEY = v
}

// GetAZURE_API_KEY returns the AZURE_API_KEY field value
func (o *STTConfigForm) GetAZURE_API_KEY() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AZURE_API_KEY
}

// GetAZURE_API_KEYOk returns a tuple with the AZURE_API_KEY field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetAZURE_API_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AZURE_API_KEY, true
}

// SetAZURE_API_KEY sets field value
func (o *STTConfigForm) SetAZURE_API_KEY(v string) {
	o.AZURE_API_KEY = v
}

// GetAZURE_REGION returns the AZURE_REGION field value
func (o *STTConfigForm) GetAZURE_REGION() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AZURE_REGION
}

// GetAZURE_REGIONOk returns a tuple with the AZURE_REGION field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetAZURE_REGIONOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AZURE_REGION, true
}

// SetAZURE_REGION sets field value
func (o *STTConfigForm) SetAZURE_REGION(v string) {
	o.AZURE_REGION = v
}

// GetAZURE_LOCALES returns the AZURE_LOCALES field value
func (o *STTConfigForm) GetAZURE_LOCALES() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AZURE_LOCALES
}

// GetAZURE_LOCALESOk returns a tuple with the AZURE_LOCALES field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetAZURE_LOCALESOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AZURE_LOCALES, true
}

// SetAZURE_LOCALES sets field value
func (o *STTConfigForm) SetAZURE_LOCALES(v string) {
	o.AZURE_LOCALES = v
}

// GetAZURE_BASE_URL returns the AZURE_BASE_URL field value
func (o *STTConfigForm) GetAZURE_BASE_URL() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AZURE_BASE_URL
}

// GetAZURE_BASE_URLOk returns a tuple with the AZURE_BASE_URL field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetAZURE_BASE_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AZURE_BASE_URL, true
}

// SetAZURE_BASE_URL sets field value
func (o *STTConfigForm) SetAZURE_BASE_URL(v string) {
	o.AZURE_BASE_URL = v
}

// GetAZURE_MAX_SPEAKERS returns the AZURE_MAX_SPEAKERS field value
func (o *STTConfigForm) GetAZURE_MAX_SPEAKERS() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AZURE_MAX_SPEAKERS
}

// GetAZURE_MAX_SPEAKERSOk returns a tuple with the AZURE_MAX_SPEAKERS field value
// and a boolean to check if the value has been set.
func (o *STTConfigForm) GetAZURE_MAX_SPEAKERSOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AZURE_MAX_SPEAKERS, true
}

// SetAZURE_MAX_SPEAKERS sets field value
func (o *STTConfigForm) SetAZURE_MAX_SPEAKERS(v string) {
	o.AZURE_MAX_SPEAKERS = v
}

func (o STTConfigForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o STTConfigForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["OPENAI_API_BASE_URL"] = o.OPENAI_API_BASE_URL
	toSerialize["OPENAI_API_KEY"] = o.OPENAI_API_KEY
	toSerialize["ENGINE"] = o.ENGINE
	toSerialize["MODEL"] = o.MODEL
	if !IsNil(o.SUPPORTED_CONTENT_TYPES) {
		toSerialize["SUPPORTED_CONTENT_TYPES"] = o.SUPPORTED_CONTENT_TYPES
	}
	toSerialize["WHISPER_MODEL"] = o.WHISPER_MODEL
	toSerialize["DEEPGRAM_API_KEY"] = o.DEEPGRAM_API_KEY
	toSerialize["AZURE_API_KEY"] = o.AZURE_API_KEY
	toSerialize["AZURE_REGION"] = o.AZURE_REGION
	toSerialize["AZURE_LOCALES"] = o.AZURE_LOCALES
	toSerialize["AZURE_BASE_URL"] = o.AZURE_BASE_URL
	toSerialize["AZURE_MAX_SPEAKERS"] = o.AZURE_MAX_SPEAKERS
	return toSerialize, nil
}

func (o *STTConfigForm) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"OPENAI_API_BASE_URL",
		"OPENAI_API_KEY",
		"ENGINE",
		"MODEL",
		"WHISPER_MODEL",
		"DEEPGRAM_API_KEY",
		"AZURE_API_KEY",
		"AZURE_REGION",
		"AZURE_LOCALES",
		"AZURE_BASE_URL",
		"AZURE_MAX_SPEAKERS",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSTTConfigForm := _STTConfigForm{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSTTConfigForm)

	if err != nil {
		return err
	}

	*o = STTConfigForm(varSTTConfigForm)

	return err
}

type NullableSTTConfigForm struct {
	value *STTConfigForm
	isSet bool
}

func (v NullableSTTConfigForm) Get() *STTConfigForm {
	return v.value
}

func (v *NullableSTTConfigForm) Set(val *STTConfigForm) {
	v.value = val
	v.isSet = true
}

func (v NullableSTTConfigForm) IsSet() bool {
	return v.isSet
}

func (v *NullableSTTConfigForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSTTConfigForm(val *STTConfigForm) *NullableSTTConfigForm {
	return &NullableSTTConfigForm{value: val, isSet: true}
}

func (v NullableSTTConfigForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSTTConfigForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


