/*
Open WebUI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openwebui

import (
	"encoding/json"
)

// checks if the OpenWebuiRoutersRetrievalConfigForm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenWebuiRoutersRetrievalConfigForm{}

// OpenWebuiRoutersRetrievalConfigForm struct for OpenWebuiRoutersRetrievalConfigForm
type OpenWebuiRoutersRetrievalConfigForm struct {
	RAG_TEMPLATE NullableString `json:"RAG_TEMPLATE,omitempty"`
	TOP_K NullableInt32 `json:"TOP_K,omitempty"`
	BYPASS_EMBEDDING_AND_RETRIEVAL NullableBool `json:"BYPASS_EMBEDDING_AND_RETRIEVAL,omitempty"`
	RAG_FULL_CONTEXT NullableBool `json:"RAG_FULL_CONTEXT,omitempty"`
	ENABLE_RAG_HYBRID_SEARCH NullableBool `json:"ENABLE_RAG_HYBRID_SEARCH,omitempty"`
	TOP_K_RERANKER NullableInt32 `json:"TOP_K_RERANKER,omitempty"`
	RELEVANCE_THRESHOLD NullableFloat32 `json:"RELEVANCE_THRESHOLD,omitempty"`
	HYBRIDBM25WEIGHT NullableFloat32 `json:"HYBRID_BM25_WEIGHT,omitempty"`
	CONTENT_EXTRACTION_ENGINE NullableString `json:"CONTENT_EXTRACTION_ENGINE,omitempty"`
	PDF_EXTRACT_IMAGES NullableBool `json:"PDF_EXTRACT_IMAGES,omitempty"`
	DATALAB_MARKER_API_KEY NullableString `json:"DATALAB_MARKER_API_KEY,omitempty"`
	DATALAB_MARKER_LANGS NullableString `json:"DATALAB_MARKER_LANGS,omitempty"`
	DATALAB_MARKER_SKIP_CACHE NullableBool `json:"DATALAB_MARKER_SKIP_CACHE,omitempty"`
	DATALAB_MARKER_FORCE_OCR NullableBool `json:"DATALAB_MARKER_FORCE_OCR,omitempty"`
	DATALAB_MARKER_PAGINATE NullableBool `json:"DATALAB_MARKER_PAGINATE,omitempty"`
	DATALAB_MARKER_STRIP_EXISTING_OCR NullableBool `json:"DATALAB_MARKER_STRIP_EXISTING_OCR,omitempty"`
	DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION NullableBool `json:"DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION,omitempty"`
	DATALAB_MARKER_USE_LLM NullableBool `json:"DATALAB_MARKER_USE_LLM,omitempty"`
	DATALAB_MARKER_OUTPUT_FORMAT NullableString `json:"DATALAB_MARKER_OUTPUT_FORMAT,omitempty"`
	EXTERNAL_DOCUMENT_LOADER_URL NullableString `json:"EXTERNAL_DOCUMENT_LOADER_URL,omitempty"`
	EXTERNAL_DOCUMENT_LOADER_API_KEY NullableString `json:"EXTERNAL_DOCUMENT_LOADER_API_KEY,omitempty"`
	TIKA_SERVER_URL NullableString `json:"TIKA_SERVER_URL,omitempty"`
	DOCLING_SERVER_URL NullableString `json:"DOCLING_SERVER_URL,omitempty"`
	DOCLING_OCR_ENGINE NullableString `json:"DOCLING_OCR_ENGINE,omitempty"`
	DOCLING_OCR_LANG NullableString `json:"DOCLING_OCR_LANG,omitempty"`
	DOCLING_DO_PICTURE_DESCRIPTION NullableBool `json:"DOCLING_DO_PICTURE_DESCRIPTION,omitempty"`
	DOCLING_PICTURE_DESCRIPTION_MODE NullableString `json:"DOCLING_PICTURE_DESCRIPTION_MODE,omitempty"`
	DOCLING_PICTURE_DESCRIPTION_LOCAL map[string]interface{} `json:"DOCLING_PICTURE_DESCRIPTION_LOCAL,omitempty"`
	DOCLING_PICTURE_DESCRIPTION_API map[string]interface{} `json:"DOCLING_PICTURE_DESCRIPTION_API,omitempty"`
	DOCUMENT_INTELLIGENCE_ENDPOINT NullableString `json:"DOCUMENT_INTELLIGENCE_ENDPOINT,omitempty"`
	DOCUMENT_INTELLIGENCE_KEY NullableString `json:"DOCUMENT_INTELLIGENCE_KEY,omitempty"`
	MISTRAL_OCR_API_KEY NullableString `json:"MISTRAL_OCR_API_KEY,omitempty"`
	RAG_RERANKING_MODEL NullableString `json:"RAG_RERANKING_MODEL,omitempty"`
	RAG_RERANKING_ENGINE NullableString `json:"RAG_RERANKING_ENGINE,omitempty"`
	RAG_EXTERNAL_RERANKER_URL NullableString `json:"RAG_EXTERNAL_RERANKER_URL,omitempty"`
	RAG_EXTERNAL_RERANKER_API_KEY NullableString `json:"RAG_EXTERNAL_RERANKER_API_KEY,omitempty"`
	TEXT_SPLITTER NullableString `json:"TEXT_SPLITTER,omitempty"`
	CHUNK_SIZE NullableInt32 `json:"CHUNK_SIZE,omitempty"`
	CHUNK_OVERLAP NullableInt32 `json:"CHUNK_OVERLAP,omitempty"`
	FILE_MAX_SIZE NullableInt32 `json:"FILE_MAX_SIZE,omitempty"`
	FILE_MAX_COUNT NullableInt32 `json:"FILE_MAX_COUNT,omitempty"`
	FILE_IMAGE_COMPRESSION_WIDTH NullableInt32 `json:"FILE_IMAGE_COMPRESSION_WIDTH,omitempty"`
	FILE_IMAGE_COMPRESSION_HEIGHT NullableInt32 `json:"FILE_IMAGE_COMPRESSION_HEIGHT,omitempty"`
	ALLOWED_FILE_EXTENSIONS []string `json:"ALLOWED_FILE_EXTENSIONS,omitempty"`
	ENABLE_GOOGLE_DRIVE_INTEGRATION NullableBool `json:"ENABLE_GOOGLE_DRIVE_INTEGRATION,omitempty"`
	ENABLE_ONEDRIVE_INTEGRATION NullableBool `json:"ENABLE_ONEDRIVE_INTEGRATION,omitempty"`
	Web NullableWebConfig `json:"web,omitempty"`
}

// NewOpenWebuiRoutersRetrievalConfigForm instantiates a new OpenWebuiRoutersRetrievalConfigForm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenWebuiRoutersRetrievalConfigForm() *OpenWebuiRoutersRetrievalConfigForm {
	this := OpenWebuiRoutersRetrievalConfigForm{}
	return &this
}

// NewOpenWebuiRoutersRetrievalConfigFormWithDefaults instantiates a new OpenWebuiRoutersRetrievalConfigForm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenWebuiRoutersRetrievalConfigFormWithDefaults() *OpenWebuiRoutersRetrievalConfigForm {
	this := OpenWebuiRoutersRetrievalConfigForm{}
	return &this
}

// GetRAG_TEMPLATE returns the RAG_TEMPLATE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_TEMPLATE() string {
	if o == nil || IsNil(o.RAG_TEMPLATE.Get()) {
		var ret string
		return ret
	}
	return *o.RAG_TEMPLATE.Get()
}

// GetRAG_TEMPLATEOk returns a tuple with the RAG_TEMPLATE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_TEMPLATEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RAG_TEMPLATE.Get(), o.RAG_TEMPLATE.IsSet()
}

// HasRAG_TEMPLATE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasRAG_TEMPLATE() bool {
	if o != nil && o.RAG_TEMPLATE.IsSet() {
		return true
	}

	return false
}

// SetRAG_TEMPLATE gets a reference to the given NullableString and assigns it to the RAG_TEMPLATE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_TEMPLATE(v string) {
	o.RAG_TEMPLATE.Set(&v)
}
// SetRAG_TEMPLATENil sets the value for RAG_TEMPLATE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_TEMPLATENil() {
	o.RAG_TEMPLATE.Set(nil)
}

// UnsetRAG_TEMPLATE ensures that no value is present for RAG_TEMPLATE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetRAG_TEMPLATE() {
	o.RAG_TEMPLATE.Unset()
}

// GetTOP_K returns the TOP_K field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTOP_K() int32 {
	if o == nil || IsNil(o.TOP_K.Get()) {
		var ret int32
		return ret
	}
	return *o.TOP_K.Get()
}

// GetTOP_KOk returns a tuple with the TOP_K field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTOP_KOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TOP_K.Get(), o.TOP_K.IsSet()
}

// HasTOP_K returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasTOP_K() bool {
	if o != nil && o.TOP_K.IsSet() {
		return true
	}

	return false
}

// SetTOP_K gets a reference to the given NullableInt32 and assigns it to the TOP_K field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTOP_K(v int32) {
	o.TOP_K.Set(&v)
}
// SetTOP_KNil sets the value for TOP_K to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTOP_KNil() {
	o.TOP_K.Set(nil)
}

// UnsetTOP_K ensures that no value is present for TOP_K, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetTOP_K() {
	o.TOP_K.Unset()
}

// GetBYPASS_EMBEDDING_AND_RETRIEVAL returns the BYPASS_EMBEDDING_AND_RETRIEVAL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetBYPASS_EMBEDDING_AND_RETRIEVAL() bool {
	if o == nil || IsNil(o.BYPASS_EMBEDDING_AND_RETRIEVAL.Get()) {
		var ret bool
		return ret
	}
	return *o.BYPASS_EMBEDDING_AND_RETRIEVAL.Get()
}

// GetBYPASS_EMBEDDING_AND_RETRIEVALOk returns a tuple with the BYPASS_EMBEDDING_AND_RETRIEVAL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetBYPASS_EMBEDDING_AND_RETRIEVALOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.BYPASS_EMBEDDING_AND_RETRIEVAL.Get(), o.BYPASS_EMBEDDING_AND_RETRIEVAL.IsSet()
}

// HasBYPASS_EMBEDDING_AND_RETRIEVAL returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasBYPASS_EMBEDDING_AND_RETRIEVAL() bool {
	if o != nil && o.BYPASS_EMBEDDING_AND_RETRIEVAL.IsSet() {
		return true
	}

	return false
}

// SetBYPASS_EMBEDDING_AND_RETRIEVAL gets a reference to the given NullableBool and assigns it to the BYPASS_EMBEDDING_AND_RETRIEVAL field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetBYPASS_EMBEDDING_AND_RETRIEVAL(v bool) {
	o.BYPASS_EMBEDDING_AND_RETRIEVAL.Set(&v)
}
// SetBYPASS_EMBEDDING_AND_RETRIEVALNil sets the value for BYPASS_EMBEDDING_AND_RETRIEVAL to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetBYPASS_EMBEDDING_AND_RETRIEVALNil() {
	o.BYPASS_EMBEDDING_AND_RETRIEVAL.Set(nil)
}

// UnsetBYPASS_EMBEDDING_AND_RETRIEVAL ensures that no value is present for BYPASS_EMBEDDING_AND_RETRIEVAL, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetBYPASS_EMBEDDING_AND_RETRIEVAL() {
	o.BYPASS_EMBEDDING_AND_RETRIEVAL.Unset()
}

// GetRAG_FULL_CONTEXT returns the RAG_FULL_CONTEXT field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_FULL_CONTEXT() bool {
	if o == nil || IsNil(o.RAG_FULL_CONTEXT.Get()) {
		var ret bool
		return ret
	}
	return *o.RAG_FULL_CONTEXT.Get()
}

// GetRAG_FULL_CONTEXTOk returns a tuple with the RAG_FULL_CONTEXT field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_FULL_CONTEXTOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.RAG_FULL_CONTEXT.Get(), o.RAG_FULL_CONTEXT.IsSet()
}

// HasRAG_FULL_CONTEXT returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasRAG_FULL_CONTEXT() bool {
	if o != nil && o.RAG_FULL_CONTEXT.IsSet() {
		return true
	}

	return false
}

// SetRAG_FULL_CONTEXT gets a reference to the given NullableBool and assigns it to the RAG_FULL_CONTEXT field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_FULL_CONTEXT(v bool) {
	o.RAG_FULL_CONTEXT.Set(&v)
}
// SetRAG_FULL_CONTEXTNil sets the value for RAG_FULL_CONTEXT to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_FULL_CONTEXTNil() {
	o.RAG_FULL_CONTEXT.Set(nil)
}

// UnsetRAG_FULL_CONTEXT ensures that no value is present for RAG_FULL_CONTEXT, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetRAG_FULL_CONTEXT() {
	o.RAG_FULL_CONTEXT.Unset()
}

// GetENABLE_RAG_HYBRID_SEARCH returns the ENABLE_RAG_HYBRID_SEARCH field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetENABLE_RAG_HYBRID_SEARCH() bool {
	if o == nil || IsNil(o.ENABLE_RAG_HYBRID_SEARCH.Get()) {
		var ret bool
		return ret
	}
	return *o.ENABLE_RAG_HYBRID_SEARCH.Get()
}

// GetENABLE_RAG_HYBRID_SEARCHOk returns a tuple with the ENABLE_RAG_HYBRID_SEARCH field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetENABLE_RAG_HYBRID_SEARCHOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ENABLE_RAG_HYBRID_SEARCH.Get(), o.ENABLE_RAG_HYBRID_SEARCH.IsSet()
}

// HasENABLE_RAG_HYBRID_SEARCH returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasENABLE_RAG_HYBRID_SEARCH() bool {
	if o != nil && o.ENABLE_RAG_HYBRID_SEARCH.IsSet() {
		return true
	}

	return false
}

// SetENABLE_RAG_HYBRID_SEARCH gets a reference to the given NullableBool and assigns it to the ENABLE_RAG_HYBRID_SEARCH field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetENABLE_RAG_HYBRID_SEARCH(v bool) {
	o.ENABLE_RAG_HYBRID_SEARCH.Set(&v)
}
// SetENABLE_RAG_HYBRID_SEARCHNil sets the value for ENABLE_RAG_HYBRID_SEARCH to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetENABLE_RAG_HYBRID_SEARCHNil() {
	o.ENABLE_RAG_HYBRID_SEARCH.Set(nil)
}

// UnsetENABLE_RAG_HYBRID_SEARCH ensures that no value is present for ENABLE_RAG_HYBRID_SEARCH, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetENABLE_RAG_HYBRID_SEARCH() {
	o.ENABLE_RAG_HYBRID_SEARCH.Unset()
}

// GetTOP_K_RERANKER returns the TOP_K_RERANKER field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTOP_K_RERANKER() int32 {
	if o == nil || IsNil(o.TOP_K_RERANKER.Get()) {
		var ret int32
		return ret
	}
	return *o.TOP_K_RERANKER.Get()
}

// GetTOP_K_RERANKEROk returns a tuple with the TOP_K_RERANKER field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTOP_K_RERANKEROk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TOP_K_RERANKER.Get(), o.TOP_K_RERANKER.IsSet()
}

// HasTOP_K_RERANKER returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasTOP_K_RERANKER() bool {
	if o != nil && o.TOP_K_RERANKER.IsSet() {
		return true
	}

	return false
}

// SetTOP_K_RERANKER gets a reference to the given NullableInt32 and assigns it to the TOP_K_RERANKER field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTOP_K_RERANKER(v int32) {
	o.TOP_K_RERANKER.Set(&v)
}
// SetTOP_K_RERANKERNil sets the value for TOP_K_RERANKER to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTOP_K_RERANKERNil() {
	o.TOP_K_RERANKER.Set(nil)
}

// UnsetTOP_K_RERANKER ensures that no value is present for TOP_K_RERANKER, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetTOP_K_RERANKER() {
	o.TOP_K_RERANKER.Unset()
}

// GetRELEVANCE_THRESHOLD returns the RELEVANCE_THRESHOLD field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRELEVANCE_THRESHOLD() float32 {
	if o == nil || IsNil(o.RELEVANCE_THRESHOLD.Get()) {
		var ret float32
		return ret
	}
	return *o.RELEVANCE_THRESHOLD.Get()
}

// GetRELEVANCE_THRESHOLDOk returns a tuple with the RELEVANCE_THRESHOLD field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRELEVANCE_THRESHOLDOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RELEVANCE_THRESHOLD.Get(), o.RELEVANCE_THRESHOLD.IsSet()
}

// HasRELEVANCE_THRESHOLD returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasRELEVANCE_THRESHOLD() bool {
	if o != nil && o.RELEVANCE_THRESHOLD.IsSet() {
		return true
	}

	return false
}

// SetRELEVANCE_THRESHOLD gets a reference to the given NullableFloat32 and assigns it to the RELEVANCE_THRESHOLD field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRELEVANCE_THRESHOLD(v float32) {
	o.RELEVANCE_THRESHOLD.Set(&v)
}
// SetRELEVANCE_THRESHOLDNil sets the value for RELEVANCE_THRESHOLD to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRELEVANCE_THRESHOLDNil() {
	o.RELEVANCE_THRESHOLD.Set(nil)
}

// UnsetRELEVANCE_THRESHOLD ensures that no value is present for RELEVANCE_THRESHOLD, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetRELEVANCE_THRESHOLD() {
	o.RELEVANCE_THRESHOLD.Unset()
}

// GetHYBRIDBM25WEIGHT returns the HYBRIDBM25WEIGHT field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetHYBRIDBM25WEIGHT() float32 {
	if o == nil || IsNil(o.HYBRIDBM25WEIGHT.Get()) {
		var ret float32
		return ret
	}
	return *o.HYBRIDBM25WEIGHT.Get()
}

// GetHYBRIDBM25WEIGHTOk returns a tuple with the HYBRIDBM25WEIGHT field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetHYBRIDBM25WEIGHTOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.HYBRIDBM25WEIGHT.Get(), o.HYBRIDBM25WEIGHT.IsSet()
}

// HasHYBRIDBM25WEIGHT returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasHYBRIDBM25WEIGHT() bool {
	if o != nil && o.HYBRIDBM25WEIGHT.IsSet() {
		return true
	}

	return false
}

// SetHYBRIDBM25WEIGHT gets a reference to the given NullableFloat32 and assigns it to the HYBRIDBM25WEIGHT field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetHYBRIDBM25WEIGHT(v float32) {
	o.HYBRIDBM25WEIGHT.Set(&v)
}
// SetHYBRIDBM25WEIGHTNil sets the value for HYBRIDBM25WEIGHT to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetHYBRIDBM25WEIGHTNil() {
	o.HYBRIDBM25WEIGHT.Set(nil)
}

// UnsetHYBRIDBM25WEIGHT ensures that no value is present for HYBRIDBM25WEIGHT, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetHYBRIDBM25WEIGHT() {
	o.HYBRIDBM25WEIGHT.Unset()
}

// GetCONTENT_EXTRACTION_ENGINE returns the CONTENT_EXTRACTION_ENGINE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetCONTENT_EXTRACTION_ENGINE() string {
	if o == nil || IsNil(o.CONTENT_EXTRACTION_ENGINE.Get()) {
		var ret string
		return ret
	}
	return *o.CONTENT_EXTRACTION_ENGINE.Get()
}

// GetCONTENT_EXTRACTION_ENGINEOk returns a tuple with the CONTENT_EXTRACTION_ENGINE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetCONTENT_EXTRACTION_ENGINEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CONTENT_EXTRACTION_ENGINE.Get(), o.CONTENT_EXTRACTION_ENGINE.IsSet()
}

// HasCONTENT_EXTRACTION_ENGINE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasCONTENT_EXTRACTION_ENGINE() bool {
	if o != nil && o.CONTENT_EXTRACTION_ENGINE.IsSet() {
		return true
	}

	return false
}

// SetCONTENT_EXTRACTION_ENGINE gets a reference to the given NullableString and assigns it to the CONTENT_EXTRACTION_ENGINE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetCONTENT_EXTRACTION_ENGINE(v string) {
	o.CONTENT_EXTRACTION_ENGINE.Set(&v)
}
// SetCONTENT_EXTRACTION_ENGINENil sets the value for CONTENT_EXTRACTION_ENGINE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetCONTENT_EXTRACTION_ENGINENil() {
	o.CONTENT_EXTRACTION_ENGINE.Set(nil)
}

// UnsetCONTENT_EXTRACTION_ENGINE ensures that no value is present for CONTENT_EXTRACTION_ENGINE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetCONTENT_EXTRACTION_ENGINE() {
	o.CONTENT_EXTRACTION_ENGINE.Unset()
}

// GetPDF_EXTRACT_IMAGES returns the PDF_EXTRACT_IMAGES field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetPDF_EXTRACT_IMAGES() bool {
	if o == nil || IsNil(o.PDF_EXTRACT_IMAGES.Get()) {
		var ret bool
		return ret
	}
	return *o.PDF_EXTRACT_IMAGES.Get()
}

// GetPDF_EXTRACT_IMAGESOk returns a tuple with the PDF_EXTRACT_IMAGES field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetPDF_EXTRACT_IMAGESOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.PDF_EXTRACT_IMAGES.Get(), o.PDF_EXTRACT_IMAGES.IsSet()
}

// HasPDF_EXTRACT_IMAGES returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasPDF_EXTRACT_IMAGES() bool {
	if o != nil && o.PDF_EXTRACT_IMAGES.IsSet() {
		return true
	}

	return false
}

// SetPDF_EXTRACT_IMAGES gets a reference to the given NullableBool and assigns it to the PDF_EXTRACT_IMAGES field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetPDF_EXTRACT_IMAGES(v bool) {
	o.PDF_EXTRACT_IMAGES.Set(&v)
}
// SetPDF_EXTRACT_IMAGESNil sets the value for PDF_EXTRACT_IMAGES to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetPDF_EXTRACT_IMAGESNil() {
	o.PDF_EXTRACT_IMAGES.Set(nil)
}

// UnsetPDF_EXTRACT_IMAGES ensures that no value is present for PDF_EXTRACT_IMAGES, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetPDF_EXTRACT_IMAGES() {
	o.PDF_EXTRACT_IMAGES.Unset()
}

// GetDATALAB_MARKER_API_KEY returns the DATALAB_MARKER_API_KEY field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_API_KEY() string {
	if o == nil || IsNil(o.DATALAB_MARKER_API_KEY.Get()) {
		var ret string
		return ret
	}
	return *o.DATALAB_MARKER_API_KEY.Get()
}

// GetDATALAB_MARKER_API_KEYOk returns a tuple with the DATALAB_MARKER_API_KEY field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_API_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_API_KEY.Get(), o.DATALAB_MARKER_API_KEY.IsSet()
}

// HasDATALAB_MARKER_API_KEY returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_API_KEY() bool {
	if o != nil && o.DATALAB_MARKER_API_KEY.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_API_KEY gets a reference to the given NullableString and assigns it to the DATALAB_MARKER_API_KEY field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_API_KEY(v string) {
	o.DATALAB_MARKER_API_KEY.Set(&v)
}
// SetDATALAB_MARKER_API_KEYNil sets the value for DATALAB_MARKER_API_KEY to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_API_KEYNil() {
	o.DATALAB_MARKER_API_KEY.Set(nil)
}

// UnsetDATALAB_MARKER_API_KEY ensures that no value is present for DATALAB_MARKER_API_KEY, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_API_KEY() {
	o.DATALAB_MARKER_API_KEY.Unset()
}

// GetDATALAB_MARKER_LANGS returns the DATALAB_MARKER_LANGS field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_LANGS() string {
	if o == nil || IsNil(o.DATALAB_MARKER_LANGS.Get()) {
		var ret string
		return ret
	}
	return *o.DATALAB_MARKER_LANGS.Get()
}

// GetDATALAB_MARKER_LANGSOk returns a tuple with the DATALAB_MARKER_LANGS field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_LANGSOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_LANGS.Get(), o.DATALAB_MARKER_LANGS.IsSet()
}

// HasDATALAB_MARKER_LANGS returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_LANGS() bool {
	if o != nil && o.DATALAB_MARKER_LANGS.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_LANGS gets a reference to the given NullableString and assigns it to the DATALAB_MARKER_LANGS field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_LANGS(v string) {
	o.DATALAB_MARKER_LANGS.Set(&v)
}
// SetDATALAB_MARKER_LANGSNil sets the value for DATALAB_MARKER_LANGS to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_LANGSNil() {
	o.DATALAB_MARKER_LANGS.Set(nil)
}

// UnsetDATALAB_MARKER_LANGS ensures that no value is present for DATALAB_MARKER_LANGS, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_LANGS() {
	o.DATALAB_MARKER_LANGS.Unset()
}

// GetDATALAB_MARKER_SKIP_CACHE returns the DATALAB_MARKER_SKIP_CACHE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_SKIP_CACHE() bool {
	if o == nil || IsNil(o.DATALAB_MARKER_SKIP_CACHE.Get()) {
		var ret bool
		return ret
	}
	return *o.DATALAB_MARKER_SKIP_CACHE.Get()
}

// GetDATALAB_MARKER_SKIP_CACHEOk returns a tuple with the DATALAB_MARKER_SKIP_CACHE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_SKIP_CACHEOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_SKIP_CACHE.Get(), o.DATALAB_MARKER_SKIP_CACHE.IsSet()
}

// HasDATALAB_MARKER_SKIP_CACHE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_SKIP_CACHE() bool {
	if o != nil && o.DATALAB_MARKER_SKIP_CACHE.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_SKIP_CACHE gets a reference to the given NullableBool and assigns it to the DATALAB_MARKER_SKIP_CACHE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_SKIP_CACHE(v bool) {
	o.DATALAB_MARKER_SKIP_CACHE.Set(&v)
}
// SetDATALAB_MARKER_SKIP_CACHENil sets the value for DATALAB_MARKER_SKIP_CACHE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_SKIP_CACHENil() {
	o.DATALAB_MARKER_SKIP_CACHE.Set(nil)
}

// UnsetDATALAB_MARKER_SKIP_CACHE ensures that no value is present for DATALAB_MARKER_SKIP_CACHE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_SKIP_CACHE() {
	o.DATALAB_MARKER_SKIP_CACHE.Unset()
}

// GetDATALAB_MARKER_FORCE_OCR returns the DATALAB_MARKER_FORCE_OCR field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_FORCE_OCR() bool {
	if o == nil || IsNil(o.DATALAB_MARKER_FORCE_OCR.Get()) {
		var ret bool
		return ret
	}
	return *o.DATALAB_MARKER_FORCE_OCR.Get()
}

// GetDATALAB_MARKER_FORCE_OCROk returns a tuple with the DATALAB_MARKER_FORCE_OCR field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_FORCE_OCROk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_FORCE_OCR.Get(), o.DATALAB_MARKER_FORCE_OCR.IsSet()
}

// HasDATALAB_MARKER_FORCE_OCR returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_FORCE_OCR() bool {
	if o != nil && o.DATALAB_MARKER_FORCE_OCR.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_FORCE_OCR gets a reference to the given NullableBool and assigns it to the DATALAB_MARKER_FORCE_OCR field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_FORCE_OCR(v bool) {
	o.DATALAB_MARKER_FORCE_OCR.Set(&v)
}
// SetDATALAB_MARKER_FORCE_OCRNil sets the value for DATALAB_MARKER_FORCE_OCR to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_FORCE_OCRNil() {
	o.DATALAB_MARKER_FORCE_OCR.Set(nil)
}

// UnsetDATALAB_MARKER_FORCE_OCR ensures that no value is present for DATALAB_MARKER_FORCE_OCR, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_FORCE_OCR() {
	o.DATALAB_MARKER_FORCE_OCR.Unset()
}

// GetDATALAB_MARKER_PAGINATE returns the DATALAB_MARKER_PAGINATE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_PAGINATE() bool {
	if o == nil || IsNil(o.DATALAB_MARKER_PAGINATE.Get()) {
		var ret bool
		return ret
	}
	return *o.DATALAB_MARKER_PAGINATE.Get()
}

// GetDATALAB_MARKER_PAGINATEOk returns a tuple with the DATALAB_MARKER_PAGINATE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_PAGINATEOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_PAGINATE.Get(), o.DATALAB_MARKER_PAGINATE.IsSet()
}

// HasDATALAB_MARKER_PAGINATE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_PAGINATE() bool {
	if o != nil && o.DATALAB_MARKER_PAGINATE.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_PAGINATE gets a reference to the given NullableBool and assigns it to the DATALAB_MARKER_PAGINATE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_PAGINATE(v bool) {
	o.DATALAB_MARKER_PAGINATE.Set(&v)
}
// SetDATALAB_MARKER_PAGINATENil sets the value for DATALAB_MARKER_PAGINATE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_PAGINATENil() {
	o.DATALAB_MARKER_PAGINATE.Set(nil)
}

// UnsetDATALAB_MARKER_PAGINATE ensures that no value is present for DATALAB_MARKER_PAGINATE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_PAGINATE() {
	o.DATALAB_MARKER_PAGINATE.Unset()
}

// GetDATALAB_MARKER_STRIP_EXISTING_OCR returns the DATALAB_MARKER_STRIP_EXISTING_OCR field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_STRIP_EXISTING_OCR() bool {
	if o == nil || IsNil(o.DATALAB_MARKER_STRIP_EXISTING_OCR.Get()) {
		var ret bool
		return ret
	}
	return *o.DATALAB_MARKER_STRIP_EXISTING_OCR.Get()
}

// GetDATALAB_MARKER_STRIP_EXISTING_OCROk returns a tuple with the DATALAB_MARKER_STRIP_EXISTING_OCR field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_STRIP_EXISTING_OCROk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_STRIP_EXISTING_OCR.Get(), o.DATALAB_MARKER_STRIP_EXISTING_OCR.IsSet()
}

// HasDATALAB_MARKER_STRIP_EXISTING_OCR returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_STRIP_EXISTING_OCR() bool {
	if o != nil && o.DATALAB_MARKER_STRIP_EXISTING_OCR.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_STRIP_EXISTING_OCR gets a reference to the given NullableBool and assigns it to the DATALAB_MARKER_STRIP_EXISTING_OCR field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_STRIP_EXISTING_OCR(v bool) {
	o.DATALAB_MARKER_STRIP_EXISTING_OCR.Set(&v)
}
// SetDATALAB_MARKER_STRIP_EXISTING_OCRNil sets the value for DATALAB_MARKER_STRIP_EXISTING_OCR to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_STRIP_EXISTING_OCRNil() {
	o.DATALAB_MARKER_STRIP_EXISTING_OCR.Set(nil)
}

// UnsetDATALAB_MARKER_STRIP_EXISTING_OCR ensures that no value is present for DATALAB_MARKER_STRIP_EXISTING_OCR, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_STRIP_EXISTING_OCR() {
	o.DATALAB_MARKER_STRIP_EXISTING_OCR.Unset()
}

// GetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION returns the DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION() bool {
	if o == nil || IsNil(o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.Get()) {
		var ret bool
		return ret
	}
	return *o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.Get()
}

// GetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTIONOk returns a tuple with the DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.Get(), o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.IsSet()
}

// HasDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION() bool {
	if o != nil && o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION gets a reference to the given NullableBool and assigns it to the DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION(v bool) {
	o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.Set(&v)
}
// SetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTIONNil sets the value for DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTIONNil() {
	o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.Set(nil)
}

// UnsetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION ensures that no value is present for DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_DISABLE_IMAGE_EXTRACTION() {
	o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.Unset()
}

// GetDATALAB_MARKER_USE_LLM returns the DATALAB_MARKER_USE_LLM field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_USE_LLM() bool {
	if o == nil || IsNil(o.DATALAB_MARKER_USE_LLM.Get()) {
		var ret bool
		return ret
	}
	return *o.DATALAB_MARKER_USE_LLM.Get()
}

// GetDATALAB_MARKER_USE_LLMOk returns a tuple with the DATALAB_MARKER_USE_LLM field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_USE_LLMOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_USE_LLM.Get(), o.DATALAB_MARKER_USE_LLM.IsSet()
}

// HasDATALAB_MARKER_USE_LLM returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_USE_LLM() bool {
	if o != nil && o.DATALAB_MARKER_USE_LLM.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_USE_LLM gets a reference to the given NullableBool and assigns it to the DATALAB_MARKER_USE_LLM field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_USE_LLM(v bool) {
	o.DATALAB_MARKER_USE_LLM.Set(&v)
}
// SetDATALAB_MARKER_USE_LLMNil sets the value for DATALAB_MARKER_USE_LLM to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_USE_LLMNil() {
	o.DATALAB_MARKER_USE_LLM.Set(nil)
}

// UnsetDATALAB_MARKER_USE_LLM ensures that no value is present for DATALAB_MARKER_USE_LLM, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_USE_LLM() {
	o.DATALAB_MARKER_USE_LLM.Unset()
}

// GetDATALAB_MARKER_OUTPUT_FORMAT returns the DATALAB_MARKER_OUTPUT_FORMAT field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_OUTPUT_FORMAT() string {
	if o == nil || IsNil(o.DATALAB_MARKER_OUTPUT_FORMAT.Get()) {
		var ret string
		return ret
	}
	return *o.DATALAB_MARKER_OUTPUT_FORMAT.Get()
}

// GetDATALAB_MARKER_OUTPUT_FORMATOk returns a tuple with the DATALAB_MARKER_OUTPUT_FORMAT field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDATALAB_MARKER_OUTPUT_FORMATOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DATALAB_MARKER_OUTPUT_FORMAT.Get(), o.DATALAB_MARKER_OUTPUT_FORMAT.IsSet()
}

// HasDATALAB_MARKER_OUTPUT_FORMAT returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDATALAB_MARKER_OUTPUT_FORMAT() bool {
	if o != nil && o.DATALAB_MARKER_OUTPUT_FORMAT.IsSet() {
		return true
	}

	return false
}

// SetDATALAB_MARKER_OUTPUT_FORMAT gets a reference to the given NullableString and assigns it to the DATALAB_MARKER_OUTPUT_FORMAT field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_OUTPUT_FORMAT(v string) {
	o.DATALAB_MARKER_OUTPUT_FORMAT.Set(&v)
}
// SetDATALAB_MARKER_OUTPUT_FORMATNil sets the value for DATALAB_MARKER_OUTPUT_FORMAT to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDATALAB_MARKER_OUTPUT_FORMATNil() {
	o.DATALAB_MARKER_OUTPUT_FORMAT.Set(nil)
}

// UnsetDATALAB_MARKER_OUTPUT_FORMAT ensures that no value is present for DATALAB_MARKER_OUTPUT_FORMAT, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDATALAB_MARKER_OUTPUT_FORMAT() {
	o.DATALAB_MARKER_OUTPUT_FORMAT.Unset()
}

// GetEXTERNAL_DOCUMENT_LOADER_URL returns the EXTERNAL_DOCUMENT_LOADER_URL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetEXTERNAL_DOCUMENT_LOADER_URL() string {
	if o == nil || IsNil(o.EXTERNAL_DOCUMENT_LOADER_URL.Get()) {
		var ret string
		return ret
	}
	return *o.EXTERNAL_DOCUMENT_LOADER_URL.Get()
}

// GetEXTERNAL_DOCUMENT_LOADER_URLOk returns a tuple with the EXTERNAL_DOCUMENT_LOADER_URL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetEXTERNAL_DOCUMENT_LOADER_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EXTERNAL_DOCUMENT_LOADER_URL.Get(), o.EXTERNAL_DOCUMENT_LOADER_URL.IsSet()
}

// HasEXTERNAL_DOCUMENT_LOADER_URL returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasEXTERNAL_DOCUMENT_LOADER_URL() bool {
	if o != nil && o.EXTERNAL_DOCUMENT_LOADER_URL.IsSet() {
		return true
	}

	return false
}

// SetEXTERNAL_DOCUMENT_LOADER_URL gets a reference to the given NullableString and assigns it to the EXTERNAL_DOCUMENT_LOADER_URL field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetEXTERNAL_DOCUMENT_LOADER_URL(v string) {
	o.EXTERNAL_DOCUMENT_LOADER_URL.Set(&v)
}
// SetEXTERNAL_DOCUMENT_LOADER_URLNil sets the value for EXTERNAL_DOCUMENT_LOADER_URL to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetEXTERNAL_DOCUMENT_LOADER_URLNil() {
	o.EXTERNAL_DOCUMENT_LOADER_URL.Set(nil)
}

// UnsetEXTERNAL_DOCUMENT_LOADER_URL ensures that no value is present for EXTERNAL_DOCUMENT_LOADER_URL, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetEXTERNAL_DOCUMENT_LOADER_URL() {
	o.EXTERNAL_DOCUMENT_LOADER_URL.Unset()
}

// GetEXTERNAL_DOCUMENT_LOADER_API_KEY returns the EXTERNAL_DOCUMENT_LOADER_API_KEY field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetEXTERNAL_DOCUMENT_LOADER_API_KEY() string {
	if o == nil || IsNil(o.EXTERNAL_DOCUMENT_LOADER_API_KEY.Get()) {
		var ret string
		return ret
	}
	return *o.EXTERNAL_DOCUMENT_LOADER_API_KEY.Get()
}

// GetEXTERNAL_DOCUMENT_LOADER_API_KEYOk returns a tuple with the EXTERNAL_DOCUMENT_LOADER_API_KEY field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetEXTERNAL_DOCUMENT_LOADER_API_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EXTERNAL_DOCUMENT_LOADER_API_KEY.Get(), o.EXTERNAL_DOCUMENT_LOADER_API_KEY.IsSet()
}

// HasEXTERNAL_DOCUMENT_LOADER_API_KEY returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasEXTERNAL_DOCUMENT_LOADER_API_KEY() bool {
	if o != nil && o.EXTERNAL_DOCUMENT_LOADER_API_KEY.IsSet() {
		return true
	}

	return false
}

// SetEXTERNAL_DOCUMENT_LOADER_API_KEY gets a reference to the given NullableString and assigns it to the EXTERNAL_DOCUMENT_LOADER_API_KEY field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetEXTERNAL_DOCUMENT_LOADER_API_KEY(v string) {
	o.EXTERNAL_DOCUMENT_LOADER_API_KEY.Set(&v)
}
// SetEXTERNAL_DOCUMENT_LOADER_API_KEYNil sets the value for EXTERNAL_DOCUMENT_LOADER_API_KEY to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetEXTERNAL_DOCUMENT_LOADER_API_KEYNil() {
	o.EXTERNAL_DOCUMENT_LOADER_API_KEY.Set(nil)
}

// UnsetEXTERNAL_DOCUMENT_LOADER_API_KEY ensures that no value is present for EXTERNAL_DOCUMENT_LOADER_API_KEY, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetEXTERNAL_DOCUMENT_LOADER_API_KEY() {
	o.EXTERNAL_DOCUMENT_LOADER_API_KEY.Unset()
}

// GetTIKA_SERVER_URL returns the TIKA_SERVER_URL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTIKA_SERVER_URL() string {
	if o == nil || IsNil(o.TIKA_SERVER_URL.Get()) {
		var ret string
		return ret
	}
	return *o.TIKA_SERVER_URL.Get()
}

// GetTIKA_SERVER_URLOk returns a tuple with the TIKA_SERVER_URL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTIKA_SERVER_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TIKA_SERVER_URL.Get(), o.TIKA_SERVER_URL.IsSet()
}

// HasTIKA_SERVER_URL returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasTIKA_SERVER_URL() bool {
	if o != nil && o.TIKA_SERVER_URL.IsSet() {
		return true
	}

	return false
}

// SetTIKA_SERVER_URL gets a reference to the given NullableString and assigns it to the TIKA_SERVER_URL field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTIKA_SERVER_URL(v string) {
	o.TIKA_SERVER_URL.Set(&v)
}
// SetTIKA_SERVER_URLNil sets the value for TIKA_SERVER_URL to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTIKA_SERVER_URLNil() {
	o.TIKA_SERVER_URL.Set(nil)
}

// UnsetTIKA_SERVER_URL ensures that no value is present for TIKA_SERVER_URL, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetTIKA_SERVER_URL() {
	o.TIKA_SERVER_URL.Unset()
}

// GetDOCLING_SERVER_URL returns the DOCLING_SERVER_URL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_SERVER_URL() string {
	if o == nil || IsNil(o.DOCLING_SERVER_URL.Get()) {
		var ret string
		return ret
	}
	return *o.DOCLING_SERVER_URL.Get()
}

// GetDOCLING_SERVER_URLOk returns a tuple with the DOCLING_SERVER_URL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_SERVER_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOCLING_SERVER_URL.Get(), o.DOCLING_SERVER_URL.IsSet()
}

// HasDOCLING_SERVER_URL returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCLING_SERVER_URL() bool {
	if o != nil && o.DOCLING_SERVER_URL.IsSet() {
		return true
	}

	return false
}

// SetDOCLING_SERVER_URL gets a reference to the given NullableString and assigns it to the DOCLING_SERVER_URL field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_SERVER_URL(v string) {
	o.DOCLING_SERVER_URL.Set(&v)
}
// SetDOCLING_SERVER_URLNil sets the value for DOCLING_SERVER_URL to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_SERVER_URLNil() {
	o.DOCLING_SERVER_URL.Set(nil)
}

// UnsetDOCLING_SERVER_URL ensures that no value is present for DOCLING_SERVER_URL, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDOCLING_SERVER_URL() {
	o.DOCLING_SERVER_URL.Unset()
}

// GetDOCLING_OCR_ENGINE returns the DOCLING_OCR_ENGINE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_OCR_ENGINE() string {
	if o == nil || IsNil(o.DOCLING_OCR_ENGINE.Get()) {
		var ret string
		return ret
	}
	return *o.DOCLING_OCR_ENGINE.Get()
}

// GetDOCLING_OCR_ENGINEOk returns a tuple with the DOCLING_OCR_ENGINE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_OCR_ENGINEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOCLING_OCR_ENGINE.Get(), o.DOCLING_OCR_ENGINE.IsSet()
}

// HasDOCLING_OCR_ENGINE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCLING_OCR_ENGINE() bool {
	if o != nil && o.DOCLING_OCR_ENGINE.IsSet() {
		return true
	}

	return false
}

// SetDOCLING_OCR_ENGINE gets a reference to the given NullableString and assigns it to the DOCLING_OCR_ENGINE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_OCR_ENGINE(v string) {
	o.DOCLING_OCR_ENGINE.Set(&v)
}
// SetDOCLING_OCR_ENGINENil sets the value for DOCLING_OCR_ENGINE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_OCR_ENGINENil() {
	o.DOCLING_OCR_ENGINE.Set(nil)
}

// UnsetDOCLING_OCR_ENGINE ensures that no value is present for DOCLING_OCR_ENGINE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDOCLING_OCR_ENGINE() {
	o.DOCLING_OCR_ENGINE.Unset()
}

// GetDOCLING_OCR_LANG returns the DOCLING_OCR_LANG field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_OCR_LANG() string {
	if o == nil || IsNil(o.DOCLING_OCR_LANG.Get()) {
		var ret string
		return ret
	}
	return *o.DOCLING_OCR_LANG.Get()
}

// GetDOCLING_OCR_LANGOk returns a tuple with the DOCLING_OCR_LANG field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_OCR_LANGOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOCLING_OCR_LANG.Get(), o.DOCLING_OCR_LANG.IsSet()
}

// HasDOCLING_OCR_LANG returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCLING_OCR_LANG() bool {
	if o != nil && o.DOCLING_OCR_LANG.IsSet() {
		return true
	}

	return false
}

// SetDOCLING_OCR_LANG gets a reference to the given NullableString and assigns it to the DOCLING_OCR_LANG field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_OCR_LANG(v string) {
	o.DOCLING_OCR_LANG.Set(&v)
}
// SetDOCLING_OCR_LANGNil sets the value for DOCLING_OCR_LANG to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_OCR_LANGNil() {
	o.DOCLING_OCR_LANG.Set(nil)
}

// UnsetDOCLING_OCR_LANG ensures that no value is present for DOCLING_OCR_LANG, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDOCLING_OCR_LANG() {
	o.DOCLING_OCR_LANG.Unset()
}

// GetDOCLING_DO_PICTURE_DESCRIPTION returns the DOCLING_DO_PICTURE_DESCRIPTION field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_DO_PICTURE_DESCRIPTION() bool {
	if o == nil || IsNil(o.DOCLING_DO_PICTURE_DESCRIPTION.Get()) {
		var ret bool
		return ret
	}
	return *o.DOCLING_DO_PICTURE_DESCRIPTION.Get()
}

// GetDOCLING_DO_PICTURE_DESCRIPTIONOk returns a tuple with the DOCLING_DO_PICTURE_DESCRIPTION field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_DO_PICTURE_DESCRIPTIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOCLING_DO_PICTURE_DESCRIPTION.Get(), o.DOCLING_DO_PICTURE_DESCRIPTION.IsSet()
}

// HasDOCLING_DO_PICTURE_DESCRIPTION returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCLING_DO_PICTURE_DESCRIPTION() bool {
	if o != nil && o.DOCLING_DO_PICTURE_DESCRIPTION.IsSet() {
		return true
	}

	return false
}

// SetDOCLING_DO_PICTURE_DESCRIPTION gets a reference to the given NullableBool and assigns it to the DOCLING_DO_PICTURE_DESCRIPTION field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_DO_PICTURE_DESCRIPTION(v bool) {
	o.DOCLING_DO_PICTURE_DESCRIPTION.Set(&v)
}
// SetDOCLING_DO_PICTURE_DESCRIPTIONNil sets the value for DOCLING_DO_PICTURE_DESCRIPTION to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_DO_PICTURE_DESCRIPTIONNil() {
	o.DOCLING_DO_PICTURE_DESCRIPTION.Set(nil)
}

// UnsetDOCLING_DO_PICTURE_DESCRIPTION ensures that no value is present for DOCLING_DO_PICTURE_DESCRIPTION, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDOCLING_DO_PICTURE_DESCRIPTION() {
	o.DOCLING_DO_PICTURE_DESCRIPTION.Unset()
}

// GetDOCLING_PICTURE_DESCRIPTION_MODE returns the DOCLING_PICTURE_DESCRIPTION_MODE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_PICTURE_DESCRIPTION_MODE() string {
	if o == nil || IsNil(o.DOCLING_PICTURE_DESCRIPTION_MODE.Get()) {
		var ret string
		return ret
	}
	return *o.DOCLING_PICTURE_DESCRIPTION_MODE.Get()
}

// GetDOCLING_PICTURE_DESCRIPTION_MODEOk returns a tuple with the DOCLING_PICTURE_DESCRIPTION_MODE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_PICTURE_DESCRIPTION_MODEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOCLING_PICTURE_DESCRIPTION_MODE.Get(), o.DOCLING_PICTURE_DESCRIPTION_MODE.IsSet()
}

// HasDOCLING_PICTURE_DESCRIPTION_MODE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCLING_PICTURE_DESCRIPTION_MODE() bool {
	if o != nil && o.DOCLING_PICTURE_DESCRIPTION_MODE.IsSet() {
		return true
	}

	return false
}

// SetDOCLING_PICTURE_DESCRIPTION_MODE gets a reference to the given NullableString and assigns it to the DOCLING_PICTURE_DESCRIPTION_MODE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_PICTURE_DESCRIPTION_MODE(v string) {
	o.DOCLING_PICTURE_DESCRIPTION_MODE.Set(&v)
}
// SetDOCLING_PICTURE_DESCRIPTION_MODENil sets the value for DOCLING_PICTURE_DESCRIPTION_MODE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_PICTURE_DESCRIPTION_MODENil() {
	o.DOCLING_PICTURE_DESCRIPTION_MODE.Set(nil)
}

// UnsetDOCLING_PICTURE_DESCRIPTION_MODE ensures that no value is present for DOCLING_PICTURE_DESCRIPTION_MODE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDOCLING_PICTURE_DESCRIPTION_MODE() {
	o.DOCLING_PICTURE_DESCRIPTION_MODE.Unset()
}

// GetDOCLING_PICTURE_DESCRIPTION_LOCAL returns the DOCLING_PICTURE_DESCRIPTION_LOCAL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_PICTURE_DESCRIPTION_LOCAL() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.DOCLING_PICTURE_DESCRIPTION_LOCAL
}

// GetDOCLING_PICTURE_DESCRIPTION_LOCALOk returns a tuple with the DOCLING_PICTURE_DESCRIPTION_LOCAL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_PICTURE_DESCRIPTION_LOCALOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DOCLING_PICTURE_DESCRIPTION_LOCAL) {
		return map[string]interface{}{}, false
	}
	return o.DOCLING_PICTURE_DESCRIPTION_LOCAL, true
}

// HasDOCLING_PICTURE_DESCRIPTION_LOCAL returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCLING_PICTURE_DESCRIPTION_LOCAL() bool {
	if o != nil && !IsNil(o.DOCLING_PICTURE_DESCRIPTION_LOCAL) {
		return true
	}

	return false
}

// SetDOCLING_PICTURE_DESCRIPTION_LOCAL gets a reference to the given map[string]interface{} and assigns it to the DOCLING_PICTURE_DESCRIPTION_LOCAL field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_PICTURE_DESCRIPTION_LOCAL(v map[string]interface{}) {
	o.DOCLING_PICTURE_DESCRIPTION_LOCAL = v
}

// GetDOCLING_PICTURE_DESCRIPTION_API returns the DOCLING_PICTURE_DESCRIPTION_API field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_PICTURE_DESCRIPTION_API() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.DOCLING_PICTURE_DESCRIPTION_API
}

// GetDOCLING_PICTURE_DESCRIPTION_APIOk returns a tuple with the DOCLING_PICTURE_DESCRIPTION_API field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCLING_PICTURE_DESCRIPTION_APIOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DOCLING_PICTURE_DESCRIPTION_API) {
		return map[string]interface{}{}, false
	}
	return o.DOCLING_PICTURE_DESCRIPTION_API, true
}

// HasDOCLING_PICTURE_DESCRIPTION_API returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCLING_PICTURE_DESCRIPTION_API() bool {
	if o != nil && !IsNil(o.DOCLING_PICTURE_DESCRIPTION_API) {
		return true
	}

	return false
}

// SetDOCLING_PICTURE_DESCRIPTION_API gets a reference to the given map[string]interface{} and assigns it to the DOCLING_PICTURE_DESCRIPTION_API field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCLING_PICTURE_DESCRIPTION_API(v map[string]interface{}) {
	o.DOCLING_PICTURE_DESCRIPTION_API = v
}

// GetDOCUMENT_INTELLIGENCE_ENDPOINT returns the DOCUMENT_INTELLIGENCE_ENDPOINT field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCUMENT_INTELLIGENCE_ENDPOINT() string {
	if o == nil || IsNil(o.DOCUMENT_INTELLIGENCE_ENDPOINT.Get()) {
		var ret string
		return ret
	}
	return *o.DOCUMENT_INTELLIGENCE_ENDPOINT.Get()
}

// GetDOCUMENT_INTELLIGENCE_ENDPOINTOk returns a tuple with the DOCUMENT_INTELLIGENCE_ENDPOINT field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCUMENT_INTELLIGENCE_ENDPOINTOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOCUMENT_INTELLIGENCE_ENDPOINT.Get(), o.DOCUMENT_INTELLIGENCE_ENDPOINT.IsSet()
}

// HasDOCUMENT_INTELLIGENCE_ENDPOINT returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCUMENT_INTELLIGENCE_ENDPOINT() bool {
	if o != nil && o.DOCUMENT_INTELLIGENCE_ENDPOINT.IsSet() {
		return true
	}

	return false
}

// SetDOCUMENT_INTELLIGENCE_ENDPOINT gets a reference to the given NullableString and assigns it to the DOCUMENT_INTELLIGENCE_ENDPOINT field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCUMENT_INTELLIGENCE_ENDPOINT(v string) {
	o.DOCUMENT_INTELLIGENCE_ENDPOINT.Set(&v)
}
// SetDOCUMENT_INTELLIGENCE_ENDPOINTNil sets the value for DOCUMENT_INTELLIGENCE_ENDPOINT to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCUMENT_INTELLIGENCE_ENDPOINTNil() {
	o.DOCUMENT_INTELLIGENCE_ENDPOINT.Set(nil)
}

// UnsetDOCUMENT_INTELLIGENCE_ENDPOINT ensures that no value is present for DOCUMENT_INTELLIGENCE_ENDPOINT, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDOCUMENT_INTELLIGENCE_ENDPOINT() {
	o.DOCUMENT_INTELLIGENCE_ENDPOINT.Unset()
}

// GetDOCUMENT_INTELLIGENCE_KEY returns the DOCUMENT_INTELLIGENCE_KEY field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCUMENT_INTELLIGENCE_KEY() string {
	if o == nil || IsNil(o.DOCUMENT_INTELLIGENCE_KEY.Get()) {
		var ret string
		return ret
	}
	return *o.DOCUMENT_INTELLIGENCE_KEY.Get()
}

// GetDOCUMENT_INTELLIGENCE_KEYOk returns a tuple with the DOCUMENT_INTELLIGENCE_KEY field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetDOCUMENT_INTELLIGENCE_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DOCUMENT_INTELLIGENCE_KEY.Get(), o.DOCUMENT_INTELLIGENCE_KEY.IsSet()
}

// HasDOCUMENT_INTELLIGENCE_KEY returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasDOCUMENT_INTELLIGENCE_KEY() bool {
	if o != nil && o.DOCUMENT_INTELLIGENCE_KEY.IsSet() {
		return true
	}

	return false
}

// SetDOCUMENT_INTELLIGENCE_KEY gets a reference to the given NullableString and assigns it to the DOCUMENT_INTELLIGENCE_KEY field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCUMENT_INTELLIGENCE_KEY(v string) {
	o.DOCUMENT_INTELLIGENCE_KEY.Set(&v)
}
// SetDOCUMENT_INTELLIGENCE_KEYNil sets the value for DOCUMENT_INTELLIGENCE_KEY to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetDOCUMENT_INTELLIGENCE_KEYNil() {
	o.DOCUMENT_INTELLIGENCE_KEY.Set(nil)
}

// UnsetDOCUMENT_INTELLIGENCE_KEY ensures that no value is present for DOCUMENT_INTELLIGENCE_KEY, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetDOCUMENT_INTELLIGENCE_KEY() {
	o.DOCUMENT_INTELLIGENCE_KEY.Unset()
}

// GetMISTRAL_OCR_API_KEY returns the MISTRAL_OCR_API_KEY field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetMISTRAL_OCR_API_KEY() string {
	if o == nil || IsNil(o.MISTRAL_OCR_API_KEY.Get()) {
		var ret string
		return ret
	}
	return *o.MISTRAL_OCR_API_KEY.Get()
}

// GetMISTRAL_OCR_API_KEYOk returns a tuple with the MISTRAL_OCR_API_KEY field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetMISTRAL_OCR_API_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MISTRAL_OCR_API_KEY.Get(), o.MISTRAL_OCR_API_KEY.IsSet()
}

// HasMISTRAL_OCR_API_KEY returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasMISTRAL_OCR_API_KEY() bool {
	if o != nil && o.MISTRAL_OCR_API_KEY.IsSet() {
		return true
	}

	return false
}

// SetMISTRAL_OCR_API_KEY gets a reference to the given NullableString and assigns it to the MISTRAL_OCR_API_KEY field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetMISTRAL_OCR_API_KEY(v string) {
	o.MISTRAL_OCR_API_KEY.Set(&v)
}
// SetMISTRAL_OCR_API_KEYNil sets the value for MISTRAL_OCR_API_KEY to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetMISTRAL_OCR_API_KEYNil() {
	o.MISTRAL_OCR_API_KEY.Set(nil)
}

// UnsetMISTRAL_OCR_API_KEY ensures that no value is present for MISTRAL_OCR_API_KEY, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetMISTRAL_OCR_API_KEY() {
	o.MISTRAL_OCR_API_KEY.Unset()
}

// GetRAG_RERANKING_MODEL returns the RAG_RERANKING_MODEL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_RERANKING_MODEL() string {
	if o == nil || IsNil(o.RAG_RERANKING_MODEL.Get()) {
		var ret string
		return ret
	}
	return *o.RAG_RERANKING_MODEL.Get()
}

// GetRAG_RERANKING_MODELOk returns a tuple with the RAG_RERANKING_MODEL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_RERANKING_MODELOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RAG_RERANKING_MODEL.Get(), o.RAG_RERANKING_MODEL.IsSet()
}

// HasRAG_RERANKING_MODEL returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasRAG_RERANKING_MODEL() bool {
	if o != nil && o.RAG_RERANKING_MODEL.IsSet() {
		return true
	}

	return false
}

// SetRAG_RERANKING_MODEL gets a reference to the given NullableString and assigns it to the RAG_RERANKING_MODEL field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_RERANKING_MODEL(v string) {
	o.RAG_RERANKING_MODEL.Set(&v)
}
// SetRAG_RERANKING_MODELNil sets the value for RAG_RERANKING_MODEL to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_RERANKING_MODELNil() {
	o.RAG_RERANKING_MODEL.Set(nil)
}

// UnsetRAG_RERANKING_MODEL ensures that no value is present for RAG_RERANKING_MODEL, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetRAG_RERANKING_MODEL() {
	o.RAG_RERANKING_MODEL.Unset()
}

// GetRAG_RERANKING_ENGINE returns the RAG_RERANKING_ENGINE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_RERANKING_ENGINE() string {
	if o == nil || IsNil(o.RAG_RERANKING_ENGINE.Get()) {
		var ret string
		return ret
	}
	return *o.RAG_RERANKING_ENGINE.Get()
}

// GetRAG_RERANKING_ENGINEOk returns a tuple with the RAG_RERANKING_ENGINE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_RERANKING_ENGINEOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RAG_RERANKING_ENGINE.Get(), o.RAG_RERANKING_ENGINE.IsSet()
}

// HasRAG_RERANKING_ENGINE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasRAG_RERANKING_ENGINE() bool {
	if o != nil && o.RAG_RERANKING_ENGINE.IsSet() {
		return true
	}

	return false
}

// SetRAG_RERANKING_ENGINE gets a reference to the given NullableString and assigns it to the RAG_RERANKING_ENGINE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_RERANKING_ENGINE(v string) {
	o.RAG_RERANKING_ENGINE.Set(&v)
}
// SetRAG_RERANKING_ENGINENil sets the value for RAG_RERANKING_ENGINE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_RERANKING_ENGINENil() {
	o.RAG_RERANKING_ENGINE.Set(nil)
}

// UnsetRAG_RERANKING_ENGINE ensures that no value is present for RAG_RERANKING_ENGINE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetRAG_RERANKING_ENGINE() {
	o.RAG_RERANKING_ENGINE.Unset()
}

// GetRAG_EXTERNAL_RERANKER_URL returns the RAG_EXTERNAL_RERANKER_URL field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_EXTERNAL_RERANKER_URL() string {
	if o == nil || IsNil(o.RAG_EXTERNAL_RERANKER_URL.Get()) {
		var ret string
		return ret
	}
	return *o.RAG_EXTERNAL_RERANKER_URL.Get()
}

// GetRAG_EXTERNAL_RERANKER_URLOk returns a tuple with the RAG_EXTERNAL_RERANKER_URL field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_EXTERNAL_RERANKER_URLOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RAG_EXTERNAL_RERANKER_URL.Get(), o.RAG_EXTERNAL_RERANKER_URL.IsSet()
}

// HasRAG_EXTERNAL_RERANKER_URL returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasRAG_EXTERNAL_RERANKER_URL() bool {
	if o != nil && o.RAG_EXTERNAL_RERANKER_URL.IsSet() {
		return true
	}

	return false
}

// SetRAG_EXTERNAL_RERANKER_URL gets a reference to the given NullableString and assigns it to the RAG_EXTERNAL_RERANKER_URL field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_EXTERNAL_RERANKER_URL(v string) {
	o.RAG_EXTERNAL_RERANKER_URL.Set(&v)
}
// SetRAG_EXTERNAL_RERANKER_URLNil sets the value for RAG_EXTERNAL_RERANKER_URL to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_EXTERNAL_RERANKER_URLNil() {
	o.RAG_EXTERNAL_RERANKER_URL.Set(nil)
}

// UnsetRAG_EXTERNAL_RERANKER_URL ensures that no value is present for RAG_EXTERNAL_RERANKER_URL, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetRAG_EXTERNAL_RERANKER_URL() {
	o.RAG_EXTERNAL_RERANKER_URL.Unset()
}

// GetRAG_EXTERNAL_RERANKER_API_KEY returns the RAG_EXTERNAL_RERANKER_API_KEY field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_EXTERNAL_RERANKER_API_KEY() string {
	if o == nil || IsNil(o.RAG_EXTERNAL_RERANKER_API_KEY.Get()) {
		var ret string
		return ret
	}
	return *o.RAG_EXTERNAL_RERANKER_API_KEY.Get()
}

// GetRAG_EXTERNAL_RERANKER_API_KEYOk returns a tuple with the RAG_EXTERNAL_RERANKER_API_KEY field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetRAG_EXTERNAL_RERANKER_API_KEYOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RAG_EXTERNAL_RERANKER_API_KEY.Get(), o.RAG_EXTERNAL_RERANKER_API_KEY.IsSet()
}

// HasRAG_EXTERNAL_RERANKER_API_KEY returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasRAG_EXTERNAL_RERANKER_API_KEY() bool {
	if o != nil && o.RAG_EXTERNAL_RERANKER_API_KEY.IsSet() {
		return true
	}

	return false
}

// SetRAG_EXTERNAL_RERANKER_API_KEY gets a reference to the given NullableString and assigns it to the RAG_EXTERNAL_RERANKER_API_KEY field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_EXTERNAL_RERANKER_API_KEY(v string) {
	o.RAG_EXTERNAL_RERANKER_API_KEY.Set(&v)
}
// SetRAG_EXTERNAL_RERANKER_API_KEYNil sets the value for RAG_EXTERNAL_RERANKER_API_KEY to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetRAG_EXTERNAL_RERANKER_API_KEYNil() {
	o.RAG_EXTERNAL_RERANKER_API_KEY.Set(nil)
}

// UnsetRAG_EXTERNAL_RERANKER_API_KEY ensures that no value is present for RAG_EXTERNAL_RERANKER_API_KEY, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetRAG_EXTERNAL_RERANKER_API_KEY() {
	o.RAG_EXTERNAL_RERANKER_API_KEY.Unset()
}

// GetTEXT_SPLITTER returns the TEXT_SPLITTER field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTEXT_SPLITTER() string {
	if o == nil || IsNil(o.TEXT_SPLITTER.Get()) {
		var ret string
		return ret
	}
	return *o.TEXT_SPLITTER.Get()
}

// GetTEXT_SPLITTEROk returns a tuple with the TEXT_SPLITTER field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetTEXT_SPLITTEROk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TEXT_SPLITTER.Get(), o.TEXT_SPLITTER.IsSet()
}

// HasTEXT_SPLITTER returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasTEXT_SPLITTER() bool {
	if o != nil && o.TEXT_SPLITTER.IsSet() {
		return true
	}

	return false
}

// SetTEXT_SPLITTER gets a reference to the given NullableString and assigns it to the TEXT_SPLITTER field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTEXT_SPLITTER(v string) {
	o.TEXT_SPLITTER.Set(&v)
}
// SetTEXT_SPLITTERNil sets the value for TEXT_SPLITTER to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetTEXT_SPLITTERNil() {
	o.TEXT_SPLITTER.Set(nil)
}

// UnsetTEXT_SPLITTER ensures that no value is present for TEXT_SPLITTER, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetTEXT_SPLITTER() {
	o.TEXT_SPLITTER.Unset()
}

// GetCHUNK_SIZE returns the CHUNK_SIZE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetCHUNK_SIZE() int32 {
	if o == nil || IsNil(o.CHUNK_SIZE.Get()) {
		var ret int32
		return ret
	}
	return *o.CHUNK_SIZE.Get()
}

// GetCHUNK_SIZEOk returns a tuple with the CHUNK_SIZE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetCHUNK_SIZEOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CHUNK_SIZE.Get(), o.CHUNK_SIZE.IsSet()
}

// HasCHUNK_SIZE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasCHUNK_SIZE() bool {
	if o != nil && o.CHUNK_SIZE.IsSet() {
		return true
	}

	return false
}

// SetCHUNK_SIZE gets a reference to the given NullableInt32 and assigns it to the CHUNK_SIZE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetCHUNK_SIZE(v int32) {
	o.CHUNK_SIZE.Set(&v)
}
// SetCHUNK_SIZENil sets the value for CHUNK_SIZE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetCHUNK_SIZENil() {
	o.CHUNK_SIZE.Set(nil)
}

// UnsetCHUNK_SIZE ensures that no value is present for CHUNK_SIZE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetCHUNK_SIZE() {
	o.CHUNK_SIZE.Unset()
}

// GetCHUNK_OVERLAP returns the CHUNK_OVERLAP field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetCHUNK_OVERLAP() int32 {
	if o == nil || IsNil(o.CHUNK_OVERLAP.Get()) {
		var ret int32
		return ret
	}
	return *o.CHUNK_OVERLAP.Get()
}

// GetCHUNK_OVERLAPOk returns a tuple with the CHUNK_OVERLAP field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetCHUNK_OVERLAPOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CHUNK_OVERLAP.Get(), o.CHUNK_OVERLAP.IsSet()
}

// HasCHUNK_OVERLAP returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasCHUNK_OVERLAP() bool {
	if o != nil && o.CHUNK_OVERLAP.IsSet() {
		return true
	}

	return false
}

// SetCHUNK_OVERLAP gets a reference to the given NullableInt32 and assigns it to the CHUNK_OVERLAP field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetCHUNK_OVERLAP(v int32) {
	o.CHUNK_OVERLAP.Set(&v)
}
// SetCHUNK_OVERLAPNil sets the value for CHUNK_OVERLAP to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetCHUNK_OVERLAPNil() {
	o.CHUNK_OVERLAP.Set(nil)
}

// UnsetCHUNK_OVERLAP ensures that no value is present for CHUNK_OVERLAP, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetCHUNK_OVERLAP() {
	o.CHUNK_OVERLAP.Unset()
}

// GetFILE_MAX_SIZE returns the FILE_MAX_SIZE field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_MAX_SIZE() int32 {
	if o == nil || IsNil(o.FILE_MAX_SIZE.Get()) {
		var ret int32
		return ret
	}
	return *o.FILE_MAX_SIZE.Get()
}

// GetFILE_MAX_SIZEOk returns a tuple with the FILE_MAX_SIZE field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_MAX_SIZEOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FILE_MAX_SIZE.Get(), o.FILE_MAX_SIZE.IsSet()
}

// HasFILE_MAX_SIZE returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasFILE_MAX_SIZE() bool {
	if o != nil && o.FILE_MAX_SIZE.IsSet() {
		return true
	}

	return false
}

// SetFILE_MAX_SIZE gets a reference to the given NullableInt32 and assigns it to the FILE_MAX_SIZE field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_MAX_SIZE(v int32) {
	o.FILE_MAX_SIZE.Set(&v)
}
// SetFILE_MAX_SIZENil sets the value for FILE_MAX_SIZE to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_MAX_SIZENil() {
	o.FILE_MAX_SIZE.Set(nil)
}

// UnsetFILE_MAX_SIZE ensures that no value is present for FILE_MAX_SIZE, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetFILE_MAX_SIZE() {
	o.FILE_MAX_SIZE.Unset()
}

// GetFILE_MAX_COUNT returns the FILE_MAX_COUNT field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_MAX_COUNT() int32 {
	if o == nil || IsNil(o.FILE_MAX_COUNT.Get()) {
		var ret int32
		return ret
	}
	return *o.FILE_MAX_COUNT.Get()
}

// GetFILE_MAX_COUNTOk returns a tuple with the FILE_MAX_COUNT field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_MAX_COUNTOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FILE_MAX_COUNT.Get(), o.FILE_MAX_COUNT.IsSet()
}

// HasFILE_MAX_COUNT returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasFILE_MAX_COUNT() bool {
	if o != nil && o.FILE_MAX_COUNT.IsSet() {
		return true
	}

	return false
}

// SetFILE_MAX_COUNT gets a reference to the given NullableInt32 and assigns it to the FILE_MAX_COUNT field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_MAX_COUNT(v int32) {
	o.FILE_MAX_COUNT.Set(&v)
}
// SetFILE_MAX_COUNTNil sets the value for FILE_MAX_COUNT to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_MAX_COUNTNil() {
	o.FILE_MAX_COUNT.Set(nil)
}

// UnsetFILE_MAX_COUNT ensures that no value is present for FILE_MAX_COUNT, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetFILE_MAX_COUNT() {
	o.FILE_MAX_COUNT.Unset()
}

// GetFILE_IMAGE_COMPRESSION_WIDTH returns the FILE_IMAGE_COMPRESSION_WIDTH field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_IMAGE_COMPRESSION_WIDTH() int32 {
	if o == nil || IsNil(o.FILE_IMAGE_COMPRESSION_WIDTH.Get()) {
		var ret int32
		return ret
	}
	return *o.FILE_IMAGE_COMPRESSION_WIDTH.Get()
}

// GetFILE_IMAGE_COMPRESSION_WIDTHOk returns a tuple with the FILE_IMAGE_COMPRESSION_WIDTH field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_IMAGE_COMPRESSION_WIDTHOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FILE_IMAGE_COMPRESSION_WIDTH.Get(), o.FILE_IMAGE_COMPRESSION_WIDTH.IsSet()
}

// HasFILE_IMAGE_COMPRESSION_WIDTH returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasFILE_IMAGE_COMPRESSION_WIDTH() bool {
	if o != nil && o.FILE_IMAGE_COMPRESSION_WIDTH.IsSet() {
		return true
	}

	return false
}

// SetFILE_IMAGE_COMPRESSION_WIDTH gets a reference to the given NullableInt32 and assigns it to the FILE_IMAGE_COMPRESSION_WIDTH field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_IMAGE_COMPRESSION_WIDTH(v int32) {
	o.FILE_IMAGE_COMPRESSION_WIDTH.Set(&v)
}
// SetFILE_IMAGE_COMPRESSION_WIDTHNil sets the value for FILE_IMAGE_COMPRESSION_WIDTH to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_IMAGE_COMPRESSION_WIDTHNil() {
	o.FILE_IMAGE_COMPRESSION_WIDTH.Set(nil)
}

// UnsetFILE_IMAGE_COMPRESSION_WIDTH ensures that no value is present for FILE_IMAGE_COMPRESSION_WIDTH, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetFILE_IMAGE_COMPRESSION_WIDTH() {
	o.FILE_IMAGE_COMPRESSION_WIDTH.Unset()
}

// GetFILE_IMAGE_COMPRESSION_HEIGHT returns the FILE_IMAGE_COMPRESSION_HEIGHT field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_IMAGE_COMPRESSION_HEIGHT() int32 {
	if o == nil || IsNil(o.FILE_IMAGE_COMPRESSION_HEIGHT.Get()) {
		var ret int32
		return ret
	}
	return *o.FILE_IMAGE_COMPRESSION_HEIGHT.Get()
}

// GetFILE_IMAGE_COMPRESSION_HEIGHTOk returns a tuple with the FILE_IMAGE_COMPRESSION_HEIGHT field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetFILE_IMAGE_COMPRESSION_HEIGHTOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FILE_IMAGE_COMPRESSION_HEIGHT.Get(), o.FILE_IMAGE_COMPRESSION_HEIGHT.IsSet()
}

// HasFILE_IMAGE_COMPRESSION_HEIGHT returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasFILE_IMAGE_COMPRESSION_HEIGHT() bool {
	if o != nil && o.FILE_IMAGE_COMPRESSION_HEIGHT.IsSet() {
		return true
	}

	return false
}

// SetFILE_IMAGE_COMPRESSION_HEIGHT gets a reference to the given NullableInt32 and assigns it to the FILE_IMAGE_COMPRESSION_HEIGHT field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_IMAGE_COMPRESSION_HEIGHT(v int32) {
	o.FILE_IMAGE_COMPRESSION_HEIGHT.Set(&v)
}
// SetFILE_IMAGE_COMPRESSION_HEIGHTNil sets the value for FILE_IMAGE_COMPRESSION_HEIGHT to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetFILE_IMAGE_COMPRESSION_HEIGHTNil() {
	o.FILE_IMAGE_COMPRESSION_HEIGHT.Set(nil)
}

// UnsetFILE_IMAGE_COMPRESSION_HEIGHT ensures that no value is present for FILE_IMAGE_COMPRESSION_HEIGHT, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetFILE_IMAGE_COMPRESSION_HEIGHT() {
	o.FILE_IMAGE_COMPRESSION_HEIGHT.Unset()
}

// GetALLOWED_FILE_EXTENSIONS returns the ALLOWED_FILE_EXTENSIONS field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetALLOWED_FILE_EXTENSIONS() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.ALLOWED_FILE_EXTENSIONS
}

// GetALLOWED_FILE_EXTENSIONSOk returns a tuple with the ALLOWED_FILE_EXTENSIONS field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetALLOWED_FILE_EXTENSIONSOk() ([]string, bool) {
	if o == nil || IsNil(o.ALLOWED_FILE_EXTENSIONS) {
		return nil, false
	}
	return o.ALLOWED_FILE_EXTENSIONS, true
}

// HasALLOWED_FILE_EXTENSIONS returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasALLOWED_FILE_EXTENSIONS() bool {
	if o != nil && !IsNil(o.ALLOWED_FILE_EXTENSIONS) {
		return true
	}

	return false
}

// SetALLOWED_FILE_EXTENSIONS gets a reference to the given []string and assigns it to the ALLOWED_FILE_EXTENSIONS field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetALLOWED_FILE_EXTENSIONS(v []string) {
	o.ALLOWED_FILE_EXTENSIONS = v
}

// GetENABLE_GOOGLE_DRIVE_INTEGRATION returns the ENABLE_GOOGLE_DRIVE_INTEGRATION field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetENABLE_GOOGLE_DRIVE_INTEGRATION() bool {
	if o == nil || IsNil(o.ENABLE_GOOGLE_DRIVE_INTEGRATION.Get()) {
		var ret bool
		return ret
	}
	return *o.ENABLE_GOOGLE_DRIVE_INTEGRATION.Get()
}

// GetENABLE_GOOGLE_DRIVE_INTEGRATIONOk returns a tuple with the ENABLE_GOOGLE_DRIVE_INTEGRATION field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetENABLE_GOOGLE_DRIVE_INTEGRATIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ENABLE_GOOGLE_DRIVE_INTEGRATION.Get(), o.ENABLE_GOOGLE_DRIVE_INTEGRATION.IsSet()
}

// HasENABLE_GOOGLE_DRIVE_INTEGRATION returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasENABLE_GOOGLE_DRIVE_INTEGRATION() bool {
	if o != nil && o.ENABLE_GOOGLE_DRIVE_INTEGRATION.IsSet() {
		return true
	}

	return false
}

// SetENABLE_GOOGLE_DRIVE_INTEGRATION gets a reference to the given NullableBool and assigns it to the ENABLE_GOOGLE_DRIVE_INTEGRATION field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetENABLE_GOOGLE_DRIVE_INTEGRATION(v bool) {
	o.ENABLE_GOOGLE_DRIVE_INTEGRATION.Set(&v)
}
// SetENABLE_GOOGLE_DRIVE_INTEGRATIONNil sets the value for ENABLE_GOOGLE_DRIVE_INTEGRATION to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetENABLE_GOOGLE_DRIVE_INTEGRATIONNil() {
	o.ENABLE_GOOGLE_DRIVE_INTEGRATION.Set(nil)
}

// UnsetENABLE_GOOGLE_DRIVE_INTEGRATION ensures that no value is present for ENABLE_GOOGLE_DRIVE_INTEGRATION, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetENABLE_GOOGLE_DRIVE_INTEGRATION() {
	o.ENABLE_GOOGLE_DRIVE_INTEGRATION.Unset()
}

// GetENABLE_ONEDRIVE_INTEGRATION returns the ENABLE_ONEDRIVE_INTEGRATION field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetENABLE_ONEDRIVE_INTEGRATION() bool {
	if o == nil || IsNil(o.ENABLE_ONEDRIVE_INTEGRATION.Get()) {
		var ret bool
		return ret
	}
	return *o.ENABLE_ONEDRIVE_INTEGRATION.Get()
}

// GetENABLE_ONEDRIVE_INTEGRATIONOk returns a tuple with the ENABLE_ONEDRIVE_INTEGRATION field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetENABLE_ONEDRIVE_INTEGRATIONOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ENABLE_ONEDRIVE_INTEGRATION.Get(), o.ENABLE_ONEDRIVE_INTEGRATION.IsSet()
}

// HasENABLE_ONEDRIVE_INTEGRATION returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasENABLE_ONEDRIVE_INTEGRATION() bool {
	if o != nil && o.ENABLE_ONEDRIVE_INTEGRATION.IsSet() {
		return true
	}

	return false
}

// SetENABLE_ONEDRIVE_INTEGRATION gets a reference to the given NullableBool and assigns it to the ENABLE_ONEDRIVE_INTEGRATION field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetENABLE_ONEDRIVE_INTEGRATION(v bool) {
	o.ENABLE_ONEDRIVE_INTEGRATION.Set(&v)
}
// SetENABLE_ONEDRIVE_INTEGRATIONNil sets the value for ENABLE_ONEDRIVE_INTEGRATION to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetENABLE_ONEDRIVE_INTEGRATIONNil() {
	o.ENABLE_ONEDRIVE_INTEGRATION.Set(nil)
}

// UnsetENABLE_ONEDRIVE_INTEGRATION ensures that no value is present for ENABLE_ONEDRIVE_INTEGRATION, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetENABLE_ONEDRIVE_INTEGRATION() {
	o.ENABLE_ONEDRIVE_INTEGRATION.Unset()
}

// GetWeb returns the Web field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *OpenWebuiRoutersRetrievalConfigForm) GetWeb() WebConfig {
	if o == nil || IsNil(o.Web.Get()) {
		var ret WebConfig
		return ret
	}
	return *o.Web.Get()
}

// GetWebOk returns a tuple with the Web field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OpenWebuiRoutersRetrievalConfigForm) GetWebOk() (*WebConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Web.Get(), o.Web.IsSet()
}

// HasWeb returns a boolean if a field has been set.
func (o *OpenWebuiRoutersRetrievalConfigForm) HasWeb() bool {
	if o != nil && o.Web.IsSet() {
		return true
	}

	return false
}

// SetWeb gets a reference to the given NullableWebConfig and assigns it to the Web field.
func (o *OpenWebuiRoutersRetrievalConfigForm) SetWeb(v WebConfig) {
	o.Web.Set(&v)
}
// SetWebNil sets the value for Web to be an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) SetWebNil() {
	o.Web.Set(nil)
}

// UnsetWeb ensures that no value is present for Web, not even an explicit nil
func (o *OpenWebuiRoutersRetrievalConfigForm) UnsetWeb() {
	o.Web.Unset()
}

func (o OpenWebuiRoutersRetrievalConfigForm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenWebuiRoutersRetrievalConfigForm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RAG_TEMPLATE.IsSet() {
		toSerialize["RAG_TEMPLATE"] = o.RAG_TEMPLATE.Get()
	}
	if o.TOP_K.IsSet() {
		toSerialize["TOP_K"] = o.TOP_K.Get()
	}
	if o.BYPASS_EMBEDDING_AND_RETRIEVAL.IsSet() {
		toSerialize["BYPASS_EMBEDDING_AND_RETRIEVAL"] = o.BYPASS_EMBEDDING_AND_RETRIEVAL.Get()
	}
	if o.RAG_FULL_CONTEXT.IsSet() {
		toSerialize["RAG_FULL_CONTEXT"] = o.RAG_FULL_CONTEXT.Get()
	}
	if o.ENABLE_RAG_HYBRID_SEARCH.IsSet() {
		toSerialize["ENABLE_RAG_HYBRID_SEARCH"] = o.ENABLE_RAG_HYBRID_SEARCH.Get()
	}
	if o.TOP_K_RERANKER.IsSet() {
		toSerialize["TOP_K_RERANKER"] = o.TOP_K_RERANKER.Get()
	}
	if o.RELEVANCE_THRESHOLD.IsSet() {
		toSerialize["RELEVANCE_THRESHOLD"] = o.RELEVANCE_THRESHOLD.Get()
	}
	if o.HYBRIDBM25WEIGHT.IsSet() {
		toSerialize["HYBRID_BM25_WEIGHT"] = o.HYBRIDBM25WEIGHT.Get()
	}
	if o.CONTENT_EXTRACTION_ENGINE.IsSet() {
		toSerialize["CONTENT_EXTRACTION_ENGINE"] = o.CONTENT_EXTRACTION_ENGINE.Get()
	}
	if o.PDF_EXTRACT_IMAGES.IsSet() {
		toSerialize["PDF_EXTRACT_IMAGES"] = o.PDF_EXTRACT_IMAGES.Get()
	}
	if o.DATALAB_MARKER_API_KEY.IsSet() {
		toSerialize["DATALAB_MARKER_API_KEY"] = o.DATALAB_MARKER_API_KEY.Get()
	}
	if o.DATALAB_MARKER_LANGS.IsSet() {
		toSerialize["DATALAB_MARKER_LANGS"] = o.DATALAB_MARKER_LANGS.Get()
	}
	if o.DATALAB_MARKER_SKIP_CACHE.IsSet() {
		toSerialize["DATALAB_MARKER_SKIP_CACHE"] = o.DATALAB_MARKER_SKIP_CACHE.Get()
	}
	if o.DATALAB_MARKER_FORCE_OCR.IsSet() {
		toSerialize["DATALAB_MARKER_FORCE_OCR"] = o.DATALAB_MARKER_FORCE_OCR.Get()
	}
	if o.DATALAB_MARKER_PAGINATE.IsSet() {
		toSerialize["DATALAB_MARKER_PAGINATE"] = o.DATALAB_MARKER_PAGINATE.Get()
	}
	if o.DATALAB_MARKER_STRIP_EXISTING_OCR.IsSet() {
		toSerialize["DATALAB_MARKER_STRIP_EXISTING_OCR"] = o.DATALAB_MARKER_STRIP_EXISTING_OCR.Get()
	}
	if o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.IsSet() {
		toSerialize["DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION"] = o.DATALAB_MARKER_DISABLE_IMAGE_EXTRACTION.Get()
	}
	if o.DATALAB_MARKER_USE_LLM.IsSet() {
		toSerialize["DATALAB_MARKER_USE_LLM"] = o.DATALAB_MARKER_USE_LLM.Get()
	}
	if o.DATALAB_MARKER_OUTPUT_FORMAT.IsSet() {
		toSerialize["DATALAB_MARKER_OUTPUT_FORMAT"] = o.DATALAB_MARKER_OUTPUT_FORMAT.Get()
	}
	if o.EXTERNAL_DOCUMENT_LOADER_URL.IsSet() {
		toSerialize["EXTERNAL_DOCUMENT_LOADER_URL"] = o.EXTERNAL_DOCUMENT_LOADER_URL.Get()
	}
	if o.EXTERNAL_DOCUMENT_LOADER_API_KEY.IsSet() {
		toSerialize["EXTERNAL_DOCUMENT_LOADER_API_KEY"] = o.EXTERNAL_DOCUMENT_LOADER_API_KEY.Get()
	}
	if o.TIKA_SERVER_URL.IsSet() {
		toSerialize["TIKA_SERVER_URL"] = o.TIKA_SERVER_URL.Get()
	}
	if o.DOCLING_SERVER_URL.IsSet() {
		toSerialize["DOCLING_SERVER_URL"] = o.DOCLING_SERVER_URL.Get()
	}
	if o.DOCLING_OCR_ENGINE.IsSet() {
		toSerialize["DOCLING_OCR_ENGINE"] = o.DOCLING_OCR_ENGINE.Get()
	}
	if o.DOCLING_OCR_LANG.IsSet() {
		toSerialize["DOCLING_OCR_LANG"] = o.DOCLING_OCR_LANG.Get()
	}
	if o.DOCLING_DO_PICTURE_DESCRIPTION.IsSet() {
		toSerialize["DOCLING_DO_PICTURE_DESCRIPTION"] = o.DOCLING_DO_PICTURE_DESCRIPTION.Get()
	}
	if o.DOCLING_PICTURE_DESCRIPTION_MODE.IsSet() {
		toSerialize["DOCLING_PICTURE_DESCRIPTION_MODE"] = o.DOCLING_PICTURE_DESCRIPTION_MODE.Get()
	}
	if o.DOCLING_PICTURE_DESCRIPTION_LOCAL != nil {
		toSerialize["DOCLING_PICTURE_DESCRIPTION_LOCAL"] = o.DOCLING_PICTURE_DESCRIPTION_LOCAL
	}
	if o.DOCLING_PICTURE_DESCRIPTION_API != nil {
		toSerialize["DOCLING_PICTURE_DESCRIPTION_API"] = o.DOCLING_PICTURE_DESCRIPTION_API
	}
	if o.DOCUMENT_INTELLIGENCE_ENDPOINT.IsSet() {
		toSerialize["DOCUMENT_INTELLIGENCE_ENDPOINT"] = o.DOCUMENT_INTELLIGENCE_ENDPOINT.Get()
	}
	if o.DOCUMENT_INTELLIGENCE_KEY.IsSet() {
		toSerialize["DOCUMENT_INTELLIGENCE_KEY"] = o.DOCUMENT_INTELLIGENCE_KEY.Get()
	}
	if o.MISTRAL_OCR_API_KEY.IsSet() {
		toSerialize["MISTRAL_OCR_API_KEY"] = o.MISTRAL_OCR_API_KEY.Get()
	}
	if o.RAG_RERANKING_MODEL.IsSet() {
		toSerialize["RAG_RERANKING_MODEL"] = o.RAG_RERANKING_MODEL.Get()
	}
	if o.RAG_RERANKING_ENGINE.IsSet() {
		toSerialize["RAG_RERANKING_ENGINE"] = o.RAG_RERANKING_ENGINE.Get()
	}
	if o.RAG_EXTERNAL_RERANKER_URL.IsSet() {
		toSerialize["RAG_EXTERNAL_RERANKER_URL"] = o.RAG_EXTERNAL_RERANKER_URL.Get()
	}
	if o.RAG_EXTERNAL_RERANKER_API_KEY.IsSet() {
		toSerialize["RAG_EXTERNAL_RERANKER_API_KEY"] = o.RAG_EXTERNAL_RERANKER_API_KEY.Get()
	}
	if o.TEXT_SPLITTER.IsSet() {
		toSerialize["TEXT_SPLITTER"] = o.TEXT_SPLITTER.Get()
	}
	if o.CHUNK_SIZE.IsSet() {
		toSerialize["CHUNK_SIZE"] = o.CHUNK_SIZE.Get()
	}
	if o.CHUNK_OVERLAP.IsSet() {
		toSerialize["CHUNK_OVERLAP"] = o.CHUNK_OVERLAP.Get()
	}
	if o.FILE_MAX_SIZE.IsSet() {
		toSerialize["FILE_MAX_SIZE"] = o.FILE_MAX_SIZE.Get()
	}
	if o.FILE_MAX_COUNT.IsSet() {
		toSerialize["FILE_MAX_COUNT"] = o.FILE_MAX_COUNT.Get()
	}
	if o.FILE_IMAGE_COMPRESSION_WIDTH.IsSet() {
		toSerialize["FILE_IMAGE_COMPRESSION_WIDTH"] = o.FILE_IMAGE_COMPRESSION_WIDTH.Get()
	}
	if o.FILE_IMAGE_COMPRESSION_HEIGHT.IsSet() {
		toSerialize["FILE_IMAGE_COMPRESSION_HEIGHT"] = o.FILE_IMAGE_COMPRESSION_HEIGHT.Get()
	}
	if o.ALLOWED_FILE_EXTENSIONS != nil {
		toSerialize["ALLOWED_FILE_EXTENSIONS"] = o.ALLOWED_FILE_EXTENSIONS
	}
	if o.ENABLE_GOOGLE_DRIVE_INTEGRATION.IsSet() {
		toSerialize["ENABLE_GOOGLE_DRIVE_INTEGRATION"] = o.ENABLE_GOOGLE_DRIVE_INTEGRATION.Get()
	}
	if o.ENABLE_ONEDRIVE_INTEGRATION.IsSet() {
		toSerialize["ENABLE_ONEDRIVE_INTEGRATION"] = o.ENABLE_ONEDRIVE_INTEGRATION.Get()
	}
	if o.Web.IsSet() {
		toSerialize["web"] = o.Web.Get()
	}
	return toSerialize, nil
}

type NullableOpenWebuiRoutersRetrievalConfigForm struct {
	value *OpenWebuiRoutersRetrievalConfigForm
	isSet bool
}

func (v NullableOpenWebuiRoutersRetrievalConfigForm) Get() *OpenWebuiRoutersRetrievalConfigForm {
	return v.value
}

func (v *NullableOpenWebuiRoutersRetrievalConfigForm) Set(val *OpenWebuiRoutersRetrievalConfigForm) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenWebuiRoutersRetrievalConfigForm) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenWebuiRoutersRetrievalConfigForm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenWebuiRoutersRetrievalConfigForm(val *OpenWebuiRoutersRetrievalConfigForm) *NullableOpenWebuiRoutersRetrievalConfigForm {
	return &NullableOpenWebuiRoutersRetrievalConfigForm{value: val, isSet: true}
}

func (v NullableOpenWebuiRoutersRetrievalConfigForm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenWebuiRoutersRetrievalConfigForm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


